# Generated by Django 2.1.15 on 2021-12-01 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userteamrole',
            name='RoleId',
        ),
        migrations.RemoveField(
            model_name='userteamrole',
            name='TeamCode',
        ),
        migrations.RemoveField(
            model_name='userteamrole',
            name='UserName',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='UserTeamRole',
        ),
    ]
