# Generated by Django 3.2.9 on 2021-12-15 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        #('HR', '__first__'),
        ('EIT', '0002_auto_20211201_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSysTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubSysName', models.CharField(max_length=100, verbose_name='نام سیستم')),
                ('TeamCode', models.ForeignKey(db_column='TeamCode', null=True, db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='Corp', verbose_name='تیم مربوطه')),
            ],
        ),
        # migrations.CreateModel(
        #     name='Feature',
        #     fields=[
        #         ('Code', models.IntegerField(db_column='Code', primary_key=True, serialize=False, verbose_name='کد')),
        #         ('Name', models.CharField(max_length=100, verbose_name='نام ')),
        #         ('Title', models.CharField(max_length=1000, verbose_name='عنوان')),
        #         ('FullTitle', models.CharField(blank=True, max_length=4000, null=True, verbose_name='نام کامل')),
        #         ('SubSysName', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام سیستم')),
        #         ('BaseFeature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BaseFeatures', to='EIT.feature', verbose_name='ویژگی پایه')),
        #         ('OwnerFeature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OwnerFeatures', to='EIT.feature', verbose_name='مالکیت')),
        #         ('SubProductFeature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SubProductFeatures', to='EIT.feature', verbose_name='ویژگی فرعی')),
        #     ],
        # ),
    ]
