# Generated by Django 3.2.9 on 2021-12-21 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0003_feature_subsysteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='EIT_View_Feature_Leaf',
            fields=[
                ('Code', models.IntegerField(db_column='Code', primary_key=True, serialize=False, verbose_name='کد')),
                ('FullTitle', models.CharField(blank=True, max_length=4000, null=True, verbose_name='نام کامل')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی ها',
                'db_table': 'EIT_View_Feature_Leaf',
                'managed': False,
            },
        ),
        # migrations.CreateModel(
        #     name='Feature',
        #     fields=[
        #         ('Code', models.IntegerField(db_column='Code', primary_key=True, serialize=False, verbose_name='کد')),
        #         ('Name', models.CharField(max_length=100, verbose_name='نام ')),
        #         ('Title', models.CharField(max_length=1000, verbose_name='عنوان')),
        #         ('FullTitle', models.CharField(blank=True, max_length=4000, null=True, verbose_name='نام کامل')),
        #         ('SubSysName', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام سیستم')),
        #         ('BaseFeature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BaseFeatures', to='EIT.feature', verbose_name='ویژگی پایه')),
        #         ('OwnerFeature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OwnerFeatures', to='EIT.feature', verbose_name='مالکیت')),
        #         ('SubProductFeature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SubProductFeatures', to='EIT.feature', verbose_name='ویژگی فرعی')),
        #     ],
        # ),
        migrations.CreateModel(
            name='CorpVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YearNumber', models.IntegerField(verbose_name='سال')),
                ('VersionNumber', models.CharField(max_length=5, verbose_name='نسخه')),
                ('SendDate', models.DateField(verbose_name='تاریخ ارسال نسخه')),
                ('CorpCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EIT.corp', verbose_name='نام شرکت')),
            ],
            options={
                'verbose_name': 'نسخه شرکت',
                'verbose_name_plural': 'نسخه های شرکت ها',
                'db_table': 'CorpVersion',
            },
        ),
    ]
