# Generated by Django 3.2.9 on 2021-12-28 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        #('HR', '__first__'),
        ('EIT', '0004_corpversion_eit_view_feature_leaf_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsysteam',
            name='Project',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='پروژه'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, verbose_name='شناسه تسک')),
                ('CreateDate', models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ ایجاد')),
                ('InternalTime', models.DateTimeField(blank=True, null=True, verbose_name='زمان داخلی')),
                ('TaskKind', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع تسک')),
                ('Title', models.CharField(blank=True, max_length=256, null=True, verbose_name='شرح')),
                ('Status', models.CharField(blank=True, max_length=100, null=True, verbose_name='وضعیت')),
                ('EstimatedBeginDate', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع تخمین')),
                ('DueDate', models.DateTimeField(blank=True, null=True, verbose_name='موعد مقرر')),
                ('EstimatedEndDate', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان تخمین')),
                ('EstimatedWorkHours', models.CharField(blank=True, max_length=10, null=True, verbose_name='ساعت تخمین')),
                ('ActualWorkHours', models.CharField(blank=True, max_length=10, null=True, verbose_name='ساعت کارکرد')),
                ('StudyDueDate', models.CharField(blank=True, max_length=10, null=True, verbose_name='سررسید')),
                ('Version', models.CharField(blank=True, max_length=256, null=True, verbose_name='نسخه')),
                ('ParentTaskTest', models.IntegerField(blank=True, null=True, verbose_name='شناسه تسک مادر بدون ارتباط')),
                ('Note', models.CharField(blank=True, max_length=4000, null=True, verbose_name='یادداشت')),
                ('Priority', models.CharField(blank=True, max_length=100, null=True, verbose_name='اولیت')),
                ('StatusChangeDate', models.DateTimeField(blank=True, null=True, verbose_name='زمان تغییر وضعیت')),
                ('ActualBeginDate', models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ شروع')),
                ('ActualEndDate', models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ پایان')),
                ('OrderNo', models.FloatField(blank=True, null=True, verbose_name='ترتیب')),
                ('RequesterCorp', models.CharField(blank=True, max_length=100, null=True, verbose_name='شرکت درخواست کننده')),
                ('IsFinished', models.CharField(blank=True, max_length=100, null=True, verbose_name='پایان یافته است؟')),
                ('MessageId', models.IntegerField(blank=True, null=True, verbose_name='شناسه پیام')),
                ('TaskParentKind', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع پدر')),
                ('ParentTaskKind', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع وظیفه پدر')),
                ('WorkMethod', models.CharField(blank=True, max_length=100, null=True, verbose_name='روش کار')),
                ('RootTask', models.IntegerField(blank=True, null=True, verbose_name='وظیفه ریشه')),
                ('MainTaskTitle', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان تشک اصلی')),
                ('QCDate', models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ QC')),
                ('QCNote', models.CharField(blank=True, max_length=4000, null=True, verbose_name='یادداشت QC')),
                ('QCStatus', models.CharField(blank=True, max_length=100, null=True, verbose_name='وضعیت QC')),
                ('DesignTask', models.IntegerField(blank=True, null=True, verbose_name='تسک طراحی')),
                ('TFWorkItem', models.IntegerField(blank=True, null=True, verbose_name='Work Item TF')),
                ('TFChangedDate', models.DateTimeField(blank=True, null=True, verbose_name='TF Changed Date')),
                ('EstimatedStartHour', models.CharField(blank=True, max_length=6, null=True, verbose_name='ساعت شروع تخمین')),
                ('ScriptPermissionDuration', models.CharField(blank=True, max_length=10, null=True, verbose_name='مدت زمان مجوز')),
                ('CreateHour', models.CharField(blank=True, max_length=10, null=True, verbose_name='ساعت شروع')),
                ('StatusChangeHour', models.CharField(blank=True, max_length=10, null=True, verbose_name='ساعت تغییر وضعیت')),
                ('DueHour', models.CharField(blank=True, max_length=5, null=True, verbose_name='ساعت مقرر')),
                ('VersioningPriority', models.IntegerField(verbose_name='اولویت نسخه')),
                ('ParentTitle', models.CharField(blank=True, max_length=256, null=True, verbose_name='شرح مادر')),
                ('ProjectFeature', models.IntegerField(blank=True, null=True, verbose_name='پروژه ویژگی')),
                ('FinishedByBLIgnore', models.BooleanField(blank=True, default=False, null=True, verbose_name='پایان رسیدن ')),
                ('FromUser', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FromUsers', to='Corp', verbose_name='از کاربر')),
                ('OwnerTask', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OwnerTasks', to='Corp', verbose_name='کاربرتسک')),
                ('ParentTask', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ParentTasks', to='EIT.task', verbose_name='شناسه تسک مادر')),
                ('Project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EIT.subsysteam', verbose_name='نام پروژه')),
                ('QCUser', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='QCUsers', to='Corp', verbose_name=' کاربرQC ')),
                ('ToUser', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ToUsers', to='Corp', verbose_name='به کاربر')),
            ],
            options={
                'verbose_name': 'تسک',
                'verbose_name_plural': 'تسک ها',
            },
        ),
        # migrations.CreateModel(
        #     name='Feature',
        #     fields=[
        #         ('Code', models.IntegerField(db_column='Code', primary_key=True, serialize=False, verbose_name='کد')),
        #         ('Name', models.CharField(max_length=100, verbose_name='نام ')),
        #         ('Title', models.CharField(max_length=1000, verbose_name='عنوان')),
        #         ('FullTitle', models.CharField(blank=True, max_length=4000, null=True, verbose_name='نام کامل')),
        #         ('SubSysName', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام سیستم')),
        #         ('BaseFeature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BaseFeatures', to='EIT.feature', verbose_name='ویژگی پایه')),
        #         ('OwnerFeature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OwnerFeatures', to='EIT.feature', verbose_name='مالکیت')),
        #         ('SubProductFeature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SubProductFeatures', to='EIT.feature', verbose_name='ویژگی فرعی')),
        #     ],
        # ),
    ]
