# Generated by Django 3.2.9 on 2021-12-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0006_auto_20211229_1846'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='subsysteam',
        #     name='Project',
        #     field=models.CharField(blank=True, max_length=100, null=True, verbose_name='پروژه'),
        # ),
    ]
