# Generated by Django 3.2.9 on 2022-01-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0007_alter_subsysteam_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='EIT_View_Feature_Team',
            fields=[
                ('Code', models.IntegerField(db_column='Code', primary_key=True, serialize=False, verbose_name='کد')),
                ('FullTitle', models.CharField(blank=True, max_length=4000, null=True, verbose_name='نام کامل')),
                ('TeamCode', models.CharField(blank=True, max_length=3, null=True, verbose_name='کد تیم')),
                ('OwnerFeature_id', models.IntegerField(null=True, verbose_name='کد')),
            ],
            options={
                'verbose_name': 'ویژگی تیم',
                'verbose_name_plural': 'ویژگی های تیم ها',
                'db_table': 'EIT_View_Feature_Team',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='task',
            name='AppVersionText',
            field=models.CharField(max_length=100, null=True, verbose_name='نسخه برنامه'),
        ),
        migrations.AlterField(
            model_name='task',
            name='Project',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='پروژه'),
        ),
    ]
