# Generated by Django 4.0.1 on 2022-09-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0008_auto_20220112_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='EIT_View_Verion',
            fields=[
                ('VersionNumber', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'نسخه',
                'verbose_name_plural': 'نسخه ها',
                'db_table': 'EIT_View_Verion',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='StatusChangeDate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='زمان تغییر وضعیت'),
        ),
    ]
