# Generated by Django 4.0.1 on 2022-09-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0009_eit_view_verion_alter_task_statuschangedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='DueDate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='موعد مقرر'),
        ),
        migrations.AlterField(
            model_name='task',
            name='EstimatedBeginDate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ شروع تخمین'),
        ),
        migrations.AlterField(
            model_name='task',
            name='EstimatedEndDate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ پایان تخمین'),
        ),
    ]
