# Generated by Django 4.0.1 on 2023-08-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0012_feature_levelnumber_feature_parenthierarchy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='ParentHierarchy',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
    ]
