# Generated by Django 4.0.1 on 2023-08-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0013_alter_feature_parenthierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='TeamCode5',
            field=models.CharField(blank=True, default='', max_length=3, null=True),
        ),
    ]
