# Generated by Django 4.0.1 on 2023-08-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0014_feature_teamcode5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='TeamCode5',
        ),
        migrations.AlterField(
            model_name='feature',
            name='ParentHierarchy',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
