# Generated by Django 4.0.1 on 2023-08-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0015_remove_feature_teamcode5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='TeamCode',
            field=models.CharField(blank=True, default='', max_length=3, null=True),
        ),
    ]
