# Generated by Django 4.0.1 on 2025-03-14 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0016_feature_teamcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RecordDate', models.DateTimeField(auto_created=True, verbose_name='تاریخ ثبت رکورد')),
                ('MessageId', models.IntegerField(verbose_name='شناسه پیام')),
                ('Title', models.CharField(max_length=200, null=True, verbose_name='عنوان پیام')),
                ('CreateDate', models.CharField(max_length=10, null=True, verbose_name='تاریخ ایجاد پیام')),
                ('CreateTime', models.CharField(default='00:00:00', max_length=10, verbose_name='ساعت ایجاد پیام')),
                ('LastShCreateDate', models.CharField(max_length=10, null=True, verbose_name='تاریخ ایجاد آخرین پاسخ')),
                ('LastShCreateTime', models.CharField(default='00:00:00', max_length=10, verbose_name='ساعت ایجاد آخرین پاسخ')),
                ('EitWaitTime', models.CharField(max_length=50, null=True, verbose_name='زمان انتظار فناوران')),
                ('BimeWaitTime', models.CharField(max_length=50, null=True, verbose_name='زمان انتظار شرکت بیمه')),
                ('FromUser', models.CharField(max_length=50, null=True, verbose_name='کاربر مربوطه')),
                ('LastFromUser', models.CharField(max_length=50, null=True, verbose_name='آخرین کاربر مربوطه')),
                ('Source', models.CharField(max_length=50, null=True, verbose_name='مبدا پیام')),
                ('IsDeleted', models.BooleanField(default=False, verbose_name='آیا این رکورد حذف شده است')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
            },
        ),
        migrations.CreateModel(
            name='ConversationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ConversationStatus', models.CharField(max_length=30, verbose_name='وضعیت پیام')),
                ('IsFinishStatus', models.BooleanField(default=False, verbose_name='وضعیت خاتمه یافته است؟')),
            ],
            options={
                'verbose_name': 'وظعیت پیام',
                'verbose_name_plural': 'وظعیت های پیام ها',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project', models.CharField(max_length=50, verbose_name='عنوان پروژه')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه ها',
            },
        ),
        migrations.CreateModel(
            name='TaskKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskKind', models.CharField(max_length=30, verbose_name='نوع تسک')),
            ],
            options={
                'verbose_name': 'نوع تسک',
                'verbose_name_plural': 'انواع تسک ها',
            },
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskStatus', models.CharField(max_length=30, verbose_name='وضعیت تسک')),
                ('IsFinishStatus', models.BooleanField(default=False, verbose_name='وضعیت خاتمه یافته است؟')),
            ],
            options={
                'verbose_name': 'وظعیت تسک',
                'verbose_name_plural': 'وظعیت های تسک ها',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('TeamCode', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='کد تیم')),
                ('TeamName', models.CharField(max_length=20, verbose_name='نام تیم')),
            ],
            options={
                'verbose_name': 'تیم',
                'verbose_name_plural': 'تیم ها',
            },
        ),
        migrations.RemoveField(
            model_name='corpversion',
            name='CorpCode',
        ),
        migrations.DeleteModel(
            name='SubSysTeam',
        ),
        migrations.RemoveField(
            model_name='task',
            name='ParentTask',
        ),
        migrations.AlterField(
            model_name='corp',
            name='CorpName',
            field=models.CharField(max_length=50, verbose_name='نام شرکت'),
        ),
        migrations.AlterModelTable(
            name='corp',
            table=None,
        ),
        migrations.DeleteModel(
            name='CorpVersion',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddField(
            model_name='project',
            name='TeamCode',
            field=models.ForeignKey(db_column='TeamCode', null=True, on_delete=django.db.models.deletion.CASCADE, to='EIT.team', verbose_name='تیم مربوطه'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='ConversationStatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIT.conversationstatus', verbose_name='وضعیت پیام'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='FromCorpCode',
            field=models.ForeignKey(db_column='FromCorpCode', default='EIT', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='FromCorp', to='EIT.corp', verbose_name='شرکت مبدا'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='Project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIT.project', verbose_name='پروژه مرتبط'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='SourceCorp',
            field=models.ForeignKey(db_column='SourceCorpCode', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SourceCorp', to='EIT.corp', verbose_name='شرکت مرتبط'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='TeamCode',
            field=models.ForeignKey(db_column='TeamCode', null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIT.team', verbose_name='تیم مرتبط'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='ToCorpCode',
            field=models.ForeignKey(db_column='ToCorpCode', default='EIT', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='ToCorp', to='EIT.corp', verbose_name='شرکت مقصد'),
        ),
    ]
