# Generated by Django 4.0.1 on 2025-03-14 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0017_conversation_conversationstatus_project_taskkind_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('VersionNumber', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='نسخه')),
                ('CreateDate', models.CharField(max_length=10, null=True, verbose_name='تاریخ ایجاد نسخه')),
                ('CloseDate', models.CharField(max_length=10, null=True, verbose_name='تاریخ بستن نسخه')),
            ],
            options={
                'verbose_name': 'نسخه',
                'verbose_name_plural': 'نسخه ها',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, verbose_name='شناسه تسک')),
                ('Title', models.CharField(blank=True, max_length=256, null=True, verbose_name='شرح')),
                ('TaskVersion', models.CharField(blank=True, max_length=256, null=True, verbose_name='نسخه')),
                ('MessageId', models.IntegerField(blank=True, null=True, verbose_name='شناسه پیام')),
                ('ToUser', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='نام کاربری مجری')),
                ('ToUserNationalCode', models.CharField(max_length=10, verbose_name='کد ملی مجری')),
                ('FromUser', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='نام کاربری تعریف کننده تسک')),
                ('FromUserNationalCode', models.CharField(max_length=10, verbose_name='کد ملی تعریف کننده تسک')),
                ('CreateDate', models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ ایجاد')),
                ('EstimatedWorkHours', models.CharField(blank=True, max_length=10, null=True, verbose_name='ساعت تخمین')),
                ('EstimatedWorkHoursMinutes', models.IntegerField(default=0, verbose_name='ساعت تخمین به دقیقه')),
                ('ActualWorkHours', models.CharField(blank=True, max_length=10, null=True, verbose_name='ساعت کارکرد')),
                ('ActualWorkHoursMinutes', models.IntegerField(default=0, verbose_name='ساعت کارکرد به دقیقه')),
                ('ActualEndDate', models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ پایان')),
                ('IsFinished', models.BooleanField(default=False, verbose_name='پایان یافته است؟')),
                ('CorpCode', models.ForeignKey(db_column='corpCode', null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIT.corp', verbose_name='شرکت درخواست دهنده')),
                ('ParentTask', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ParentTasks', to='EIT.task', verbose_name='شناسه تسک مادر')),
                ('Project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIT.project', verbose_name='پروژه تسک')),
                ('RootTask', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RootTasks', to='EIT.task', verbose_name='شناسه تسک اصلی')),
                ('TaskKind', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIT.taskkind', verbose_name='نوع تسک')),
                ('TaskStatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIT.taskstatus', verbose_name='وضعیت')),
                ('TeamCode', models.ForeignKey(db_column='TeamCode', null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIT.team', verbose_name='تیم تسک')),
            ],
            options={
                'verbose_name': 'تسک',
                'verbose_name_plural': 'تسک ها',
            },
        ),
        migrations.CreateModel(
            name='SubSysTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubSysName', models.CharField(max_length=100, verbose_name='نام سیستم')),
                ('Project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIT.project', verbose_name='پروژه مربوطه')),
                ('TeamCode', models.ForeignKey(db_column='TeamCode', null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIT.team', verbose_name='تیم')),
            ],
        ),
        migrations.CreateModel(
            name='CorpVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YearNumber', models.IntegerField(verbose_name='سال')),
                ('SendDate', models.DateField(verbose_name='تاریخ ارسال نسخه')),
                ('CorpCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EIT.corp', verbose_name='نام شرکت')),
                ('VersionNumber', models.ForeignKey(db_column='VersionNumber', on_delete=django.db.models.deletion.CASCADE, to='EIT.version', verbose_name='نسخه')),
            ],
            options={
                'verbose_name': 'نسخه شرکت',
                'verbose_name_plural': 'نسخه های شرکت ها',
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='Task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIT.task', verbose_name='شناسه تسکر مرتبط'),
        ),
    ]
