# Generated by Django 4.0.1 on 2025-03-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0018_version_task_subsysteam_corpversion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='VersionNumber',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='نسخه'),
        ),
    ]
