# Generated by Django 4.0.1 on 2025-03-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0019_alter_version_versionnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='ActualWorkHours',
        ),
        migrations.RemoveField(
            model_name='task',
            name='CreateDate',
        ),
        migrations.RemoveField(
            model_name='task',
            name='EstimatedWorkHours',
        ),
        migrations.AddField(
            model_name='task',
            name='CreateDateTime',
            field=models.CharField(blank=True, help_text='تاریخ به شمسی است و ساعت به آن اضافه شده است', max_length=20, null=True, verbose_name='تاریخ و ساعت ایجاد'),
        ),
        migrations.AlterField(
            model_name='task',
            name='FromUserNationalCode',
            field=models.CharField(max_length=10, null=True, verbose_name='کد ملی تعریف کننده تسک'),
        ),
        migrations.AlterField(
            model_name='task',
            name='TaskVersion',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='ایتریشن تسک'),
        ),
        migrations.AlterField(
            model_name='task',
            name='ToUserNationalCode',
            field=models.CharField(max_length=10, null=True, verbose_name='کد ملی مجری'),
        ),
    ]
