# Generated by Django 4.0.1 on 2025-03-17 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0020_remove_task_actualworkhours_remove_task_createdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30, verbose_name='نوع')),
                ('KindType', models.CharField(default='TA', help_text='نوع می تواند مربوط به تسک یا درخواست یا مورد درخواست باشد', max_length=2, verbose_name='دسته بندی نوع')),
                ('KindCode', models.CharField(max_length=10, null=True, verbose_name='کد نوع')),
            ],
            options={
                'verbose_name': 'نوع تسک',
                'verbose_name_plural': 'انواع تسک ها',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, verbose_name='شناسه درخواست')),
                ('Title', models.CharField(max_length=500, verbose_name='عنوان درخواست')),
                ('IsPublic', models.BooleanField(default=False, verbose_name='ایا درخواست عمومی است؟')),
                ('CreateDate', models.CharField(help_text='تاریخ به شمسی و ساعت به آن اضافه شده است', max_length=20, verbose_name='تاریخ و ساعت ایجاد')),
                ('IsFinished', models.BooleanField(default=False, verbose_name='پایان یافته است؟')),
                ('CreatorUser', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='نام کاربری تعریف کننده درخواست')),
                ('CreatorUserNationalCode', models.CharField(max_length=10, null=True, verbose_name='کد ملی تعریف کننده درخواست')),
                ('OwnerUser', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='نام کاربری مالک درخواست')),
                ('OwnerUserNationalCode', models.CharField(max_length=10, null=True, verbose_name='کد ملی مالک درخواست')),
                ('CorpCode', models.ForeignKey(db_column='CorpCode', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FromCorpCode', to='EIT.corp', verbose_name='شرکت درخواست دهنده')),
                ('Project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIT.project', verbose_name='پروژه')),
                ('RelatedRequest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIT.request', verbose_name='درخواست مرتبط')),
                ('RequestKind', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIT.kind', verbose_name='نوع درخواست')),
            ],
            options={
                'verbose_name': 'درخواست',
                'verbose_name_plural': 'درخواست ها',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskStatus', models.CharField(max_length=30, verbose_name='وضعیت')),
                ('StatusType', models.CharField(choices=[('TA', 'تسک'), ('ME', 'پیام'), ('RE', 'درخواست'), ('RI', 'مورد درخواست')], help_text='وضعیت می تواند مربوط به تسک، پیام، درخواست یا مورد درخواست باشد', max_length=2, verbose_name='نوع وضعیت')),
                ('IsFinishStatus', models.BooleanField(default=False, verbose_name='وضعیت خاتمه یافته است؟')),
                ('StatusCode', models.CharField(max_length=50, verbose_name='کد وضعیت')),
            ],
            options={
                'verbose_name': ' وضعیت',
                'verbose_name_plural': 'وضعیت ها',
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='ActualEndDate',
            field=models.CharField(blank=True, help_text='تاریخ به شمسی است و ساعت به آن اضافه شده است', max_length=20, null=True, verbose_name='تاریخ و ساعت پایان'),
        ),
        migrations.CreateModel(
            name='TaskWorkhours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkTimeDate', models.CharField(help_text='تاریخ ایجاد مورد درخواست به شمسی و بدون ساعت است', max_length=10, verbose_name='تاریخ ایجاد')),
                ('RelatedUser', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='نام کاربری مجری')),
                ('RelatedUserNationalCode', models.CharField(max_length=10, null=True, verbose_name='کد ملی مجری')),
                ('WorkHoursMinutes', models.PositiveIntegerField(verbose_name='کارکرد به دقیقه')),
                ('Task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIT.task', verbose_name='شناسه تسک مرتبط')),
            ],
            options={
                'verbose_name': 'کارکرد تسک',
                'verbose_name_plural': 'کارکردهای تسک ها',
            },
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, verbose_name='شناسه مورد درخواست')),
                ('Title', models.CharField(max_length=500, verbose_name='عنوان مورد درخواست')),
                ('ToUser', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='نام کاربری مجری مورد درخواست')),
                ('ToNationalCode', models.CharField(max_length=10, null=True, verbose_name='کد ملی مجری مورد درخواست')),
                ('FromUser', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='نام کاربری کاربر تعریف کننده مورد درخواست')),
                ('FromUserNationalCode', models.CharField(max_length=10, null=True, verbose_name='کد ملی کاربر تعریف کننده مورد درخواست')),
                ('CreateDate', models.CharField(help_text='تاریخ ایجاد مورد درخواست به شمسی و بدون ساعت است', max_length=10, verbose_name='تاریخ ایجاد')),
                ('Request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIT.request', verbose_name='شناسه درخواست مرتبط')),
                ('RequestItemKind', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIT.kind', verbose_name='نوع درخواست')),
                ('RequestItemStatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIT.status', verbose_name='وضعیت درخواست')),
                ('Task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIT.task', verbose_name='شناسه تسک مرتبط')),
            ],
            options={
                'verbose_name': 'مورد درخواست',
                'verbose_name_plural': 'موارد درخواست',
            },
        ),
        migrations.AddField(
            model_name='request',
            name='RequestStatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIT.status', verbose_name='وضعیت درخواست'),
        ),
        migrations.AddField(
            model_name='request',
            name='TeamCode',
            field=models.ForeignKey(db_column='TeamCode', null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIT.team', verbose_name='تیم مربوطه'),
        ),
        migrations.AddField(
            model_name='request',
            name='ToCorpCode',
            field=models.ForeignKey(db_column='ToCorpCode', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ToCorpCode', to='EIT.corp', verbose_name='شرکت درخواست دهنده'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='ConversationStatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIT.status', verbose_name='وضعیت پیام'),
        ),
        migrations.AlterField(
            model_name='task',
            name='TaskKind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIT.kind', verbose_name='نوع تسک'),
        ),
        migrations.AlterField(
            model_name='task',
            name='TaskStatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIT.status', verbose_name='وضعیت'),
        ),
        migrations.DeleteModel(
            name='ConversationStatus',
        ),
        migrations.DeleteModel(
            name='TaskKind',
        ),
        migrations.DeleteModel(
            name='TaskStatus',
        ),
    ]
