# Generated by Django 4.0.1 on 2025-03-17 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0021_kind_request_status_alter_task_actualenddate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='TaskStatus',
            new_name='Title',
        ),
    ]
