# Generated by Django 4.0.1 on 2025-03-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0022_rename_taskstatus_status_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='CreateDateTime',
            new_name='CreateDate',
        ),
    ]
