# Generated by Django 4.0.1 on 2025-03-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0023_rename_createdatetime_task_createdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='StatusCode',
            field=models.CharField(max_length=50, null=True, verbose_name='کد وضعیت'),
        ),
    ]
