# Generated by Django 4.0.1 on 2025-03-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0024_alter_status_statuscode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='TeamName',
            field=models.CharField(max_length=50, verbose_name='نام تیم'),
        ),
    ]
