# Generated by Django 4.0.1 on 2025-03-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0025_alter_team_teamname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kind',
            name='Title',
            field=models.CharField(max_length=50, verbose_name='نوع'),
        ),
    ]
