# Generated by Django 4.0.1 on 2025-03-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0026_alter_kind_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kind',
            name='Title',
            field=models.CharField(max_length=100, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='status',
            name='Title',
            field=models.CharField(max_length=100, verbose_name='وضعیت'),
        ),
    ]
