# Generated by Django 4.0.1 on 2025-03-20 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0027_alter_kind_title_alter_status_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestitem',
            old_name='ToNationalCode',
            new_name='ToUserNationalCode',
        ),
    ]
