# Generated by Django 4.0.1 on 2025-03-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0028_rename_tonationalcode_requestitem_tousernationalcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='JiraId',
            field=models.IntegerField(null=True, verbose_name='شناسه تسک در جیرا'),
        ),
    ]
