# Generated by Django 4.0.1 on 2025-03-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0029_task_jiraid'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='TaskId',
            field=models.IntegerField(null=True, verbose_name='شناسه تسک در PM'),
        ),
        migrations.AlterField(
            model_name='task',
            name='Id',
            field=models.CharField(help_text='در صورتی که تسک PM باشد شناسه به صورت P-Id و در صورتی که برای جیرا باشد J-Id است. در صورتی که تسک هم در جیرا و هم در PM باشد، شناسه PM در نظر گرفته می شود', max_length=10, primary_key=True, serialize=False, verbose_name='شناسه تسک'),
        ),
        migrations.AlterField(
            model_name='task',
            name='Title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان تسک'),
        ),
    ]
