# Generated by Django 4.0.1 on 2025-03-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0030_task_taskid_alter_task_id_alter_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='TaskResolution',
            field=models.CharField(help_text='این مقدار فقط برای جیرا تعریف شده و چگونگی خاتمه تسک ها را مشخص می کند', max_length=50, null=True, verbose_name='نتیجه انجام تسک'),
        ),
    ]
