# Generated by Django 4.0.1 on 2025-03-23 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0031_task_taskresolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='StatusType',
            field=models.CharField(choices=[('TA', 'تسک'), ('RE', 'درخواست'), ('RI', 'مورد درخواست'), ('IS', 'Issue جیرا')], help_text='وضعیت می تواند مربوط به تسک، پیام، درخواست یا مورد درخواست باشد', max_length=2, verbose_name='نوع وضعیت'),
        ),
        migrations.CreateModel(
            name='TaskCorps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CorpCode', models.ForeignKey(db_column='CorpCode', on_delete=django.db.models.deletion.CASCADE, to='EIT.corp', verbose_name='شرکت درخواست دهنده')),
                ('Task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EIT.task', verbose_name='شناسه تسک')),
            ],
            options={
                'verbose_name': 'شرکت مرتبط با تسک',
                'verbose_name_plural': 'شرکت های مرتبط با تسک ها',
            },
        ),
    ]
