# Generated by Django 4.0.1 on 2025-03-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0032_alter_status_statustype_taskcorps'),
    ]

    operations = [
        migrations.AddField(
            model_name='kind',
            name='JiraKind',
            field=models.CharField(max_length=50, null=True, verbose_name='نوع معادل در جیرا'),
        ),
    ]
