# Generated by Django 4.0.1 on 2025-03-23 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0033_kind_jirakind'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='JiraId',
            new_name='IssueId',
        ),
        migrations.AddField(
            model_name='task',
            name='IssueKind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='IssueKind', to='EIT.kind', verbose_name='نوع تسک در جیرا'),
        ),
        migrations.AddField(
            model_name='task',
            name='TaskSprint',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ایتریشن تسک'),
        ),
        migrations.AlterField(
            model_name='task',
            name='TaskKind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TaskKind', to='EIT.kind', verbose_name='نوع تسک'),
        ),
        migrations.AlterField(
            model_name='task',
            name='TaskVersion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نسخه تسک'),
        ),
    ]
