# Generated by Django 4.0.1 on 2025-03-23 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0034_rename_jiraid_task_issueid_task_issuekind_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='TaskResolution',
            new_name='IssueResolution',
        ),
        migrations.AddField(
            model_name='task',
            name='IssueStatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='IssueStatus', to='EIT.status', verbose_name='وضعیت در جیرا'),
        ),
        migrations.AlterField(
            model_name='task',
            name='TaskStatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TaskStatus', to='EIT.status', verbose_name='وضعیت'),
        ),
    ]
