# Generated by Django 4.0.1 on 2025-03-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0035_rename_taskresolution_task_issueresolution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corp',
            name='CorpLatinName',
            field=models.CharField(max_length=30, null=True, verbose_name='نام لاتین شرکت بیمه'),
        ),
    ]
