# Generated by Django 4.0.1 on 2025-03-24 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0036_corp_corplatinname'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcorps',
            name='IsPrimaryRequester',
            field=models.BooleanField(default=False, verbose_name='درخواست دهنده اصلی بوده است؟'),
        ),
        migrations.AddField(
            model_name='taskcorps',
            name='RequestItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIT.requestitem', verbose_name='شناسه مورد درخواست'),
        ),
        migrations.AddField(
            model_name='taskcorps',
            name='WorkHourMinutesInvoice',
            field=models.PositiveIntegerField(default=0, verbose_name='ساعت کارکرد مندرج در صورت حساب'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskcorps',
            name='WorkHourMinutesPM',
            field=models.PositiveIntegerField(default=0, verbose_name='ساعت کارکرد ثبت شده در PM'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskcorps',
            name='WorkHourMinutesReal',
            field=models.PositiveIntegerField(default=0, verbose_name='ساعت کارکرد واقعی'),
            preserve_default=False,
        ),
    ]
