# Generated by Django 4.0.1 on 2025-03-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0037_taskcorps_isprimaryrequester_taskcorps_requestitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcorps',
            name='WorkHourMinutesInvoice',
            field=models.PositiveIntegerField(default=0, verbose_name='ساعت کارکرد مندرج در صورت حساب'),
        ),
        migrations.AlterField(
            model_name='taskcorps',
            name='WorkHourMinutesPM',
            field=models.PositiveIntegerField(default=0, verbose_name='ساعت کارکرد ثبت شده در PM'),
        ),
        migrations.AlterField(
            model_name='taskcorps',
            name='WorkHourMinutesReal',
            field=models.PositiveIntegerField(default=0, verbose_name='ساعت کارکرد واقعی'),
        ),
    ]
