# Generated by Django 4.0.1 on 2025-03-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0038_alter_taskcorps_workhourminutesinvoice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corp',
            old_name='CorpLatinName',
            new_name='EnglishName',
        ),
        migrations.AddField(
            model_name='corp',
            name='FullTitle',
            field=models.CharField(max_length=100, null=True, verbose_name='عنوان کامل شرکت بیمه'),
        ),
    ]
