# Generated by Django 4.0.1 on 2025-03-27 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0039_rename_corplatinname_corp_englishname_corp_fulltitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='VOIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CallDate', models.DateTimeField(help_text='تاریخ به میلادی و ساعت', null=True, verbose_name='زمان تماس')),
                ('CallSource', models.CharField(help_text='شماره تماس گیرنده، می تواند با صفر شروع شود', max_length=11, null=True, verbose_name='تماس گیرنده')),
                ('CallDestination', models.CharField(help_text='شماره مقصد. می تواند با صفر شروع شود', max_length=11, null=True, verbose_name='شماره مقصد')),
                ('CallDivert', models.CharField(help_text='در صورتی که تماس منتقل شده باشد، شماره انتقالی که معمولا داخلی است', max_length=11, null=True, verbose_name='شماره انتقال تماس')),
                ('RingGroup', models.CharField(help_text='مربوط به سیستم VOIP است', max_length=10, null=True, verbose_name='گروه بندی تماس')),
                ('SourceChanel', models.CharField(help_text='مربوط به سیستم VOIP است', max_length=30, null=True, verbose_name='کانال مبدا')),
                ('DestinationChanel', models.CharField(help_text='مربوط به سیستم VOIP است', max_length=30, null=True, verbose_name='کانال مقصد')),
                ('AccountCode', models.CharField(help_text='شماره اکانت مربوطه', max_length=30, null=True, verbose_name='شماره اکانت')),
                ('CallStatus', models.CharField(help_text='مشخص می کند که تماس پاسخ داده شده، پاسخ داده نشده و یا رد شده است', max_length=15, null=True, verbose_name='وضعیت تماس')),
                ('Duration', models.PositiveSmallIntegerField(help_text='مدت تماس بر حسب ثانیه', null=True, verbose_name='مدت تماس')),
                ('StringDuration', models.CharField(help_text='مدت زمان به صورت رشته ای MM:SS', max_length=10, null=True, verbose_name='مدت تماس')),
                ('InputCall', models.BooleanField(help_text='اگر تماس ورودی باشد مقدار یک و در غیر این صورت صفر است', null=True, verbose_name='تماس ورودی')),
                ('CorpName', models.CharField(help_text='نام شرکت', max_length=20, null=True, verbose_name='نام شرکت')),
                ('FromUserName', models.CharField(help_text='نام کاربر تماس گیرنده', max_length=50, null=True, verbose_name='نام کاربر تماس گیرنده')),
                ('FromUserRoleTypeCode', models.CharField(help_text='مشخص می کند که کاربر مربوطه، پشتیبان، برنامه نویس و ... است.', max_length=10, null=True, verbose_name='کد گروه سمت کاربر تماس گیرنده')),
                ('ToUserName', models.CharField(help_text='شناسه کاربری که با او تماس گرفته شده است', max_length=50, null=True, verbose_name='کد کاربر مقصد')),
                ('ToUserRoleTypeCode', models.CharField(help_text='مشخص می کند که کاربر مربوطه، پشتیبان، برنامه نویس و ... است.', max_length=10, null=True, verbose_name='کد گروه کاربر مقصد')),
                ('CorpCode', models.ForeignKey(help_text='کد شرکت', null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIT.corp', verbose_name='کد شرکت')),
                ('FromTeamCode', models.ForeignKey(help_text='کد تیم کاربر تماس گیرنده', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FromTeamCode', to='EIT.team', verbose_name='تیم کاربر تماس گیرنده')),
                ('ToTeamCode', models.ForeignKey(help_text='کد کاربری که با او تماس گرفته شده است', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ToTeamCode', to='EIT.team', verbose_name='تیم کاربر مقصد')),
            ],
            options={
                'verbose_name': 'سابقه تماس',
                'verbose_name_plural': 'سوابق تماس ها',
            },
        ),
    ]
