# Generated by Django 4.0.1 on 2025-03-27 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0040_voip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voip',
            name='CorpCode',
            field=models.ForeignKey(db_column='CorpCode', help_text='کد شرکت', null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIT.corp', verbose_name='کد شرکت'),
        ),
        migrations.AlterField(
            model_name='voip',
            name='FromTeamCode',
            field=models.ForeignKey(db_column='FromTeamCode', help_text='کد تیم کاربر تماس گیرنده', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FromTeamCode', to='EIT.team', verbose_name='تیم کاربر تماس گیرنده'),
        ),
        migrations.AlterField(
            model_name='voip',
            name='RingGroup',
            field=models.CharField(help_text='مربوط به سیستم VOIP است', max_length=30, null=True, verbose_name='گروه بندی تماس'),
        ),
        migrations.AlterField(
            model_name='voip',
            name='ToTeamCode',
            field=models.ForeignKey(db_column='ToTeamCode', help_text='کد کاربری که با او تماس گرفته شده است', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ToTeamCode', to='EIT.team', verbose_name='تیم کاربر مقصد'),
        ),
    ]
