# Generated by Django 4.0.1 on 2025-03-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0041_alter_voip_corpcode_alter_voip_fromteamcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voip',
            name='AccountCode',
            field=models.CharField(help_text='شماره اکانت مربوطه', max_length=50, null=True, verbose_name='شماره اکانت'),
        ),
        migrations.AlterField(
            model_name='voip',
            name='CallDestination',
            field=models.CharField(help_text='شماره مقصد. می تواند با صفر شروع شود', max_length=50, null=True, verbose_name='شماره مقصد'),
        ),
        migrations.AlterField(
            model_name='voip',
            name='CallSource',
            field=models.CharField(help_text='شماره تماس گیرنده، می تواند با صفر شروع شود', max_length=50, null=True, verbose_name='تماس گیرنده'),
        ),
        migrations.AlterField(
            model_name='voip',
            name='DestinationChanel',
            field=models.CharField(help_text='مربوط به سیستم VOIP است', max_length=50, null=True, verbose_name='کانال مقصد'),
        ),
        migrations.AlterField(
            model_name='voip',
            name='SourceChanel',
            field=models.CharField(help_text='مربوط به سیستم VOIP است', max_length=50, null=True, verbose_name='کانال مبدا'),
        ),
    ]
