# Generated by Django 4.0.1 on 2025-03-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0042_alter_voip_accountcode_alter_voip_calldestination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voip',
            name='Duration',
            field=models.PositiveIntegerField(help_text='مدت تماس بر حسب ثانیه', null=True, verbose_name='مدت تماس'),
        ),
    ]
