# Generated by Django 4.0.1 on 2025-03-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0043_alter_voip_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voip',
            name='Duration',
            field=models.PositiveBigIntegerField(help_text='مدت تماس بر حسب ثانیه', null=True, verbose_name='مدت تماس'),
        ),
    ]
