# Generated by Django 4.0.1 on 2025-03-28 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0045_corpversion_approvedate_corpversion_invoiceid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpversion',
            name='CorpCode',
            field=models.ForeignKey(db_column='CorpCode', on_delete=django.db.models.deletion.CASCADE, to='EIT.corp', verbose_name='نام شرکت'),
        ),
    ]
