# Generated by Django 4.0.1 on 2025-03-28 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0046_alter_corpversion_corpcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corpinvoicetask',
            old_name='IsPrimaryRequestor',
            new_name='IsPrimaryRequester',
        ),
    ]
