# Generated by Django 4.0.1 on 2025-03-28 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0047_rename_isprimaryrequestor_corpinvoicetask_isprimaryrequester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corpinvoicetask',
            old_name='FinalWorkHoursMiutes',
            new_name='FinalWorkHoursMinutes',
        ),
    ]
