# Generated by Django 4.0.1 on 2025-03-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0048_rename_finalworkhoursmiutes_corpinvoicetask_finalworkhoursminutes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='LastShCreateDate',
            new_name='LastMidifyDate',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='LastShCreateTime',
            new_name='LastModifyTime',
        ),
        migrations.AlterField(
            model_name='status',
            name='StatusType',
            field=models.CharField(choices=[('TA', 'تسک'), ('RE', 'درخواست'), ('RI', 'مورد درخواست'), ('IS', 'Issue جیرا'), ('CO', 'پیام ها')], help_text='وضعیت می تواند مربوط به تسک، پیام، درخواست یا مورد درخواست باشد', max_length=2, verbose_name='نوع وضعیت'),
        ),
    ]
