# Generated by Django 4.0.1 on 2025-03-29 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0050_task_request_task_requestitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Caption', models.CharField(max_length=50, verbose_name='عنوان')),
                ('Code', models.CharField(max_length=100, verbose_name='کد')),
                ('IsActive', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('OrderNumber', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='شماره ترتیب')),
                ('ConstValue', models.IntegerField(blank=True, null=True, verbose_name='مقدار مربوطه')),
                ('Parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EIT.constvalue', verbose_name='شناسه پدر')),
            ],
            options={
                'verbose_name': 'مقدار ثابت',
                'verbose_name_plural': 'مقادیر ثابت',
                'ordering': ['Parent_id', 'OrderNumber'],
            },
        ),
    ]
