# Generated by Django 4.0.1 on 2025-03-29 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0052_versionrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSystem',
            fields=[
                ('Code', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='نام سیستم')),
                ('Project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIT.project', verbose_name='پروژه مربوطه')),
                ('TeamCode', models.ForeignKey(db_column='TeamCode', null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIT.team', verbose_name='تیم')),
            ],
        ),
        migrations.CreateModel(
            name='VersionRequestSubsystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClientDescription', models.CharField(max_length=500, null=True, verbose_name='توضیحات مشتری')),
                ('FirstSigner', models.CharField(max_length=50, null=True, verbose_name='تایید کننده اول')),
                ('SecondSigner', models.CharField(max_length=50, null=True, verbose_name='تایید کننده دوم')),
                ('ApprovalTestSender', models.CharField(max_length=50, null=True, verbose_name='تایید کننده تست')),
                ('Owner', models.CharField(max_length=50, null=True, verbose_name='مالک درخواست')),
                ('SubSystemCode', models.ForeignKey(db_column='SubSystemCode', on_delete=django.db.models.deletion.CASCADE, to='EIT.subsystem', verbose_name='کد زیرسیستم')),
                ('TeamCode', models.ForeignKey(db_column='TeamCode', on_delete=django.db.models.deletion.CASCADE, to='EIT.team', verbose_name='کد تیم')),
                ('VersionRequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EIT.versionrequest', verbose_name='شناسه درخواست نسخه')),
                ('VersionStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EIT.kind', verbose_name='وضعیت درخواست نسخه')),
            ],
            options={
                'verbose_name': 'زیر سیستم درخواست نسخه',
                'verbose_name_plural': 'زیر سیستم های درخواست نسخه ها',
            },
        ),
        migrations.CreateModel(
            name='VersionRequestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EIT.task', verbose_name='شناسه تسک')),
                ('VersionRequestSubsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EIT.versionrequestsubsystem', verbose_name='زیرسیستم نسخه مربوطه')),
                ('VersionTaskKind', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIT.constvalue', verbose_name='نوع تسک مرتبط')),
            ],
            options={
                'verbose_name': 'تسک درخواست نسخه',
                'verbose_name_plural': 'تسک های درخواست نسخه ها',
            },
        ),
        migrations.DeleteModel(
            name='SubSysTeam',
        ),
    ]
