# Generated by Django 4.0.1 on 2025-03-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0053_subsystem_versionrequestsubsystem_versionrequesttask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='Duration',
            field=models.PositiveIntegerField(default=0, verbose_name='مدت زمان به دقیقه'),
            preserve_default=False,
        ),
    ]
