# Generated by Django 4.0.1 on 2025-03-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0054_conversation_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='MessageId',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='id',
        ),
        migrations.AddField(
            model_name='conversation',
            name='MessageCode',
            field=models.CharField(default='1', max_length=15, primary_key=True, serialize=False, verbose_name='شناسه پیام'),
            preserve_default=False,
        ),
    ]
