# Generated by Django 4.0.1 on 2025-03-31 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0055_remove_conversation_messageid_remove_conversation_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='FromCorpCode',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='Source',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='SourceCorp',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='ToCorpCode',
        ),
        migrations.AddField(
            model_name='conversation',
            name='CorpCode',
            field=models.ForeignKey(db_column='CorpCode', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Corp', to='EIT.corp', verbose_name='شرکت مربوطه'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='FromEIT',
            field=models.BooleanField(default=False, verbose_name='پیام از جانب شرکت فناوران بوده است؟'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='MessageSource',
            field=models.ForeignKey(help_text='مبدا پیام می تواند سیستم محاوره شرکت بیمه، محاوره PM یا پیام کاربران باشد', null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIT.constvalue', verbose_name='مبدا پیام'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='ReponseTime',
            field=models.CharField(default='00:00:00', max_length=10, verbose_name='ساعت پاسخ گویی پیام'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='ResponseDate',
            field=models.CharField(max_length=10, null=True, verbose_name='تاریخ پاسخگویی پیام'),
        ),
    ]
