# Generated by Django 4.0.1 on 2025-03-31 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0056_remove_conversation_fromcorpcode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='ReponseTime',
            new_name='ResponseTime',
        ),
    ]
