# Generated by Django 4.0.1 on 2025-04-01 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0058_remove_versionrequest_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='versionrequest',
            old_name='id2',
            new_name='id',
        ),
        migrations.AddField(
            model_name='versionrequestsubsystem',
            name='VersionRequest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EIT.versionrequest', verbose_name='شناسه درخواست نسخه'),
            preserve_default=False,
        ),
    ]
