# Generated by Django 4.0.1 on 2025-04-01 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0059_rename_id2_versionrequest_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='StatusType',
            field=models.CharField(choices=[('TA', 'تسک'), ('RE', 'درخواست'), ('RI', 'مورد درخواست'), ('IS', 'Issue جیرا'), ('CO', 'پیام ها'), ('VR', 'درخواست نسخه')], help_text='وضعیت می تواند مربوط به تسک، پیام، درخواست یا مورد درخواست باشد', max_length=2, verbose_name='نوع وضعیت'),
        ),
        migrations.AlterField(
            model_name='versionrequest',
            name='VersionTaskKind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EIT.kind', verbose_name='نوع نسخه'),
        ),
    ]
