# Generated by Django 4.0.1 on 2025-04-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0060_alter_status_statustype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionrequest',
            name='SendDate',
            field=models.CharField(help_text='تاریخ به شمسی در قالب YYYY/MM/DD', max_length=10, null=True, verbose_name='تاریخ ارسال'),
        ),
        migrations.AlterField(
            model_name='versionrequest',
            name='SendTime',
            field=models.TimeField(null=True, verbose_name='زمان ارسال نسخه'),
        ),
    ]
