# Generated by Django 4.0.1 on 2025-04-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0061_alter_versionrequest_senddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionrequestsubsystem',
            name='ClientDescription',
            field=models.TextField(null=True, verbose_name='توضیحات مشتری'),
        ),
    ]
