# Generated by Django 4.0.1 on 2025-04-01 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0062_alter_versionrequestsubsystem_clientdescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='versionrequestsubsystem',
            old_name='Owner',
            new_name='RequestOwner',
        ),
    ]
