# Generated by Django 4.0.1 on 2025-04-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0063_rename_owner_versionrequestsubsystem_requestowner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versionrequestsubsystem',
            name='id',
        ),
        migrations.RemoveField(
            model_name='versionrequesttask',
            name='VersionRequestSubsystem',
        ),
        migrations.AddField(
            model_name='versionrequestsubsystem',
            name='id2',
            field=models.PositiveIntegerField(default=1, help_text='این شناسه برابر با مقدار PM است و شمارنده خودکار نیست', primary_key=True, serialize=False, verbose_name='شناسه درخواست نسخه'),
            preserve_default=False,
        ),
    ]
