# Generated by Django 4.0.1 on 2025-04-01 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0064_remove_versionrequestsubsystem_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='versionrequestsubsystem',
            old_name='id2',
            new_name='id',
        ),
        migrations.AddField(
            model_name='versionrequesttask',
            name='VersionRequestSubsystem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EIT.versionrequestsubsystem', verbose_name='زیرسیستم نسخه مربوطه'),
            preserve_default=False,
        ),
    ]
