# Generated by Django 4.2.20 on 2025-04-02 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0065_rename_id2_versionrequestsubsystem_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionrequestsubsystem',
            name='VersionStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EIT.status', verbose_name='وضعیت درخواست نسخه'),
        ),
    ]
