# Generated by Django 4.2.20 on 2025-04-02 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0066_alter_versionrequestsubsystem_versionstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='CreateTime',
            field=models.CharField(max_length=10, null=True, verbose_name='ساعت ایجاد پیام'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='LastModifyTime',
            field=models.CharField(max_length=10, null=True, verbose_name='ساعت ایجاد آخرین پاسخ'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='ResponseTime',
            field=models.CharField(max_length=10, null=True, verbose_name='ساعت پاسخ گویی پیام'),
        ),
        migrations.AlterField(
            model_name='versionrequesttask',
            name='VersionRequestSubsystem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EIT.versionrequestsubsystem', verbose_name='شناسه درخواست زیرسیستم نسخه مربوطه'),
        ),
    ]
