# Generated by Django 4.2.20 on 2025-04-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0067_alter_conversation_createtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='Duration',
            field=models.PositiveIntegerField(null=True, verbose_name='مدت زمان به دقیقه'),
        ),
    ]
