# Generated by Django 4.2.20 on 2025-04-03 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0068_alter_conversation_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpinvoicetask',
            name='TeamCode',
            field=models.ForeignKey(db_column='TeamCode', default='COM', on_delete=django.db.models.deletion.CASCADE, to='EIT.team', verbose_name='کد تیم '),
            preserve_default=False,
        ),
    ]
