# Generated by Django 4.2.20 on 2025-04-03 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0069_corpinvoicetask_teamcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpinvoicetask',
            name='Task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EIT.task', verbose_name='شناسه تسک '),
        ),
        migrations.AlterField(
            model_name='corpinvoicetask',
            name='TeamCode',
            field=models.ForeignKey(db_column='TeamCode', null=True, on_delete=django.db.models.deletion.CASCADE, to='EIT.team', verbose_name='کد تیم '),
        ),
        migrations.AlterField(
            model_name='corpversion',
            name='SendDate',
            field=models.DateField(null=True, verbose_name='تاریخ ارسال نسخه'),
        ),
        migrations.AlterField(
            model_name='corpversion',
            name='YearNumber',
            field=models.IntegerField(null=True, verbose_name='سال'),
        ),
    ]
