# Generated by Django 4.2.20 on 2025-04-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0071_alter_corpversion_senddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='Title',
            field=models.CharField(max_length=500, null=True, verbose_name='عنوان پیام'),
        ),
    ]
