# Generated by Django 4.2.20 on 2025-04-29 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EIT', '0072_alter_conversation_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userstel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tel', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('UserName', models.CharField(max_length=100, verbose_name='نام کاربری')),
                ('StartDate', models.CharField(max_length=10, verbose_name='تاریخ شروع')),
                ('EndDate', models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ پایان')),
                ('StartDateMiladi', models.DateField(verbose_name='تاریخ شروع میلادی')),
                ('EndDateMiladi', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان میلادی')),
            ],
            options={
                'verbose_name': 'شماره داخلی کاربر',
                'verbose_name_plural': 'شماره های داخلی کاربران',
            },
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'قابلیت', 'verbose_name_plural': 'قابلیت ها'},
        ),
        migrations.AlterModelOptions(
            name='subsystem',
            options={'verbose_name': 'زیرسیستم', 'verbose_name_plural': 'زیرسیستم ها'},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['-VersionNumber'], 'verbose_name': 'نسخه', 'verbose_name_plural': 'نسخه ها'},
        ),
        migrations.AlterField(
            model_name='conversation',
            name='ConversationStatus',
            field=models.ForeignKey(limit_choices_to={'StatusType': 'CO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIT.status', verbose_name='وضعیت پیام'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='MessageSource',
            field=models.ForeignKey(help_text='مبدا پیام می تواند سیستم محاوره شرکت بیمه، محاوره PM یا پیام کاربران باشد', limit_choices_to={'Code__istartswith': 'MessageSource_'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIT.constvalue', verbose_name='مبدا پیام'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='TeamCode',
            field=models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='تیم'),
        ),
        migrations.AlterField(
            model_name='kind',
            name='KindType',
            field=models.CharField(choices=[('TA', 'تسک'), ('RE', 'درخواست'), ('RI', 'مورد درخواست'), ('IS', 'Issue جیرا'), ('VR', 'درخواست نسخه')], default='TA', help_text='نوع می تواند مربوط به تسک یا درخواست یا مورد درخواست باشد', max_length=2, verbose_name='دسته بندی نوع'),
        ),
        migrations.AlterField(
            model_name='request',
            name='RequestKind',
            field=models.ForeignKey(limit_choices_to={'KindType': 'RE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIT.kind', verbose_name='نوع درخواست'),
        ),
        migrations.AlterField(
            model_name='request',
            name='RequestStatus',
            field=models.ForeignKey(limit_choices_to={'StatusType': 'RE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIT.status', verbose_name='وضعیت درخواست'),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='RequestItemKind',
            field=models.ForeignKey(limit_choices_to={'KindType': 'RI'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIT.kind', verbose_name='نوع مورد درخواست'),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='RequestItemStatus',
            field=models.ForeignKey(limit_choices_to={'StatusType': 'RI'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIT.status', verbose_name='وضعیت مورد درخواست'),
        ),
        migrations.AlterField(
            model_name='task',
            name='IssueKind',
            field=models.ForeignKey(limit_choices_to={'KindType': 'IS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='IssueKind', to='EIT.kind', verbose_name='نوع تسک در جیرا'),
        ),
        migrations.AlterField(
            model_name='task',
            name='IssueStatus',
            field=models.ForeignKey(limit_choices_to={'StatusType': 'IS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='IssueStatus', to='EIT.status', verbose_name='وضعیت در جیرا'),
        ),
        migrations.AlterField(
            model_name='task',
            name='TaskKind',
            field=models.ForeignKey(limit_choices_to={'KindType': 'TA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TaskKind', to='EIT.kind', verbose_name='نوع تسک'),
        ),
        migrations.AlterField(
            model_name='task',
            name='TaskStatus',
            field=models.ForeignKey(limit_choices_to={'StatusType': 'TA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TaskStatus', to='EIT.status', verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='versionrequest',
            name='VersionTaskKind',
            field=models.ForeignKey(limit_choices_to={'KindType': 'VR'}, on_delete=django.db.models.deletion.CASCADE, to='EIT.kind', verbose_name='نوع نسخه'),
        ),
        migrations.AlterField(
            model_name='versionrequestsubsystem',
            name='VersionStatus',
            field=models.ForeignKey(limit_choices_to={'StatusType': 'VR'}, on_delete=django.db.models.deletion.CASCADE, to='EIT.status', verbose_name='وضعیت درخواست نسخه'),
        ),
        migrations.AlterField(
            model_name='versionrequesttask',
            name='VersionTaskKind',
            field=models.ForeignKey(limit_choices_to={'Code__istartswith': 'VersionTaskKind_'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIT.constvalue', verbose_name='نوع تسک مرتبط'),
        ),
        migrations.CreateModel(
            name='Corptel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TelNumber', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('CorpCode', models.ForeignKey(db_column='CorpCode', on_delete=django.db.models.deletion.CASCADE, to='EIT.corp', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'شماره شرکت بیمه ',
                'verbose_name_plural': 'شماره های شرکت های بیمه',
            },
        ),
    ]
