# Generated by Django 4.0.1 on 2022-02-24 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppName', models.CharField(max_length=200, verbose_name='نام لاتین برنامه')),
                ('AppTitle', models.CharField(max_length=200, verbose_name='عنوان برنامه')),
                ('ENGINE', models.CharField(max_length=200, null=True)),
                ('NAME', models.CharField(max_length=200, null=True)),
                ('USER', models.CharField(max_length=200, null=True)),
                ('PASSWORD', models.CharField(max_length=200, null=True)),
                ('HOST', models.CharField(max_length=200, null=True)),
                ('PORT', models.CharField(max_length=200, null=True)),
                ('OPTIONS', models.JSONField(null=True)),
            ],
            options={
                'verbose_name': 'اطلاعات برنامه',
                'verbose_name_plural': 'اطلاعات برنامه ها',
            },
        ),
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'مجوز گروه',
                'verbose_name_plural': 'مجوز گروه ها',
            },
        ),
        migrations.CreateModel(
            name='PermissionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'مجوز کاربر',
                'verbose_name_plural': 'مجوز کاربران',
            },
        ),
        migrations.CreateModel(
            name='UpdateAppInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'بروزرسانی',
                'verbose_name_plural': 'بروزرسانی اطلاعات برنامه ها',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppInfo', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='InternalAccess.appinfo')),
            ],
            options={
                'verbose_name': 'گروه کاربر',
                'verbose_name_plural': 'گروه های کاربران',
            },
        ),
    ]
