# Generated by Django 4.0.1 on 2022-02-24 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InternalAccess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionuser',
            name='Permissions',
            field=models.CharField(default=None, max_length=1000, null=True, verbose_name='مجوز ها'),
        ),
        migrations.AddField(
            model_name='permissionuser',
            name='UserName',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
