# Generated by Django 4.0.1 on 2022-02-24 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InternalAccess', '0002_permissionuser_permissions_permissionuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionuser',
            name='Permissions',
        ),
        migrations.RemoveField(
            model_name='permissionuser',
            name='UserName',
        ),
    ]
