# Generated by Django 4.0.1 on 2022-02-25 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InternalAccess', '0003_remove_permissionuser_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='AppInfo',
        ),
    ]
