# Generated by Django 4.0.1 on 2022-04-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InternalAccess', '0004_remove_usergroup_appinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='permissiongroup',
            options={'verbose_name': 'مجوز گروه', 'verbose_name_plural': 'دسترسی گروه ها'},
        ),
        migrations.AlterModelOptions(
            name='permissionuser',
            options={'verbose_name': 'مجوز کاربر', 'verbose_name_plural': 'دسترسی کاربران'},
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'verbose_name': 'گروه کاربر', 'verbose_name_plural': 'اعضای گروه ها'},
        ),
        migrations.AddField(
            model_name='appinfo',
            name='APPIP',
            field=models.GenericIPAddressField(null=True, verbose_name='آیپی سرور برنامه'),
        ),
        migrations.AddField(
            model_name='appinfo',
            name='APPPORT',
            field=models.IntegerField(null=True, verbose_name='پورت سرور برنامه'),
        ),
        migrations.AddField(
            model_name='appinfo',
            name='APPSCHEMA',
            field=models.CharField(default='http://', max_length=10),
        ),
    ]
