# Generated by Django 4.0.1 on 2022-04-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InternalAccess', '0005_virtualusers_alter_permissiongroup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appinfo',
            name='APPIP',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='آیپی سرور برنامه'),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='APPPORT',
            field=models.IntegerField(blank=True, null=True, verbose_name='پورت سرور برنامه'),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='APPSCHEMA',
            field=models.CharField(blank=True, default='http://', max_length=10, verbose_name='اس اس ال برنامه'),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='ENGINE',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='HOST',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='NAME',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='OPTIONS',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='PASSWORD',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='PORT',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='USER',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
