# Generated by Django 4.0.1 on 2024-10-14 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppDocId', models.IntegerField(blank=True, verbose_name='شناسه')),
                ('Priority', models.CharField(blank=True, max_length=100, verbose_name='اولویت')),
                ('DocState', models.CharField(blank=True, max_length=100, verbose_name='وضعیت')),
                ('DocumentTitle', models.CharField(blank=True, max_length=500, null=True, verbose_name='نوع')),
                ('AppCode', models.CharField(blank=True, max_length=200, null=True, verbose_name='مسیر برنامه')),
                ('DocumentOwner', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReceiveDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ دریافت')),
                ('IsRead', models.BooleanField(blank=True, default=False, verbose_name='خوانده شده')),
                ('SendDate', models.DateTimeField(blank=True, default=None, null=True, verbose_name='تاریخ ارسال')),
                ('InboxOwner', models.CharField(blank=True, max_length=100, verbose_name='کاربر')),
                ('SenderUser', models.CharField(blank=True, max_length=100, verbose_name='کاربر ارسال کننده')),
                ('DueDate', models.DateField(blank=True, null=True, verbose_name='مهلت پاسخ گویی')),
                ('PersonalDueDate', models.DateField(blank=True, null=True, verbose_name='زمان انجام کار')),
                ('IsVisible', models.BooleanField(default=True, verbose_name='قابل مشاهده')),
                ('DocumentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Documents', to='Cartable.document', verbose_name='شناسه ')),
                ('PreviousFlow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DocumenrFlows', to='Cartable.documentflow', verbose_name='قبلی ')),
            ],
        ),
    ]
