# Generated by Django 4.0.1 on 2024-10-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartable', '0002_comment_documentflow_readdate_documentflow_roleid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentflow',
            name='WorkFlowStep',
            field=models.CharField(max_length=100, null=True, verbose_name='مرحله'),
        ),
    ]
