# Generated by Django 4.0.1 on 2024-11-03 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cartable', '0003_alter_documentflow_workflowstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Person', models.CharField(max_length=100)),
                ('ViewDate', models.DateTimeField(auto_now_add=True)),
                ('CommentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cartable.comment')),
            ],
        ),
    ]
