# Generated by Django 4.0.1 on 2024-11-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartable', '0004_commentviewhistory'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='commentviewhistory',
            constraint=models.UniqueConstraint(fields=('CommentId', 'Person'), name='UniqueView'),
        ),
    ]
