# Generated by Django 4.0.1 on 2025-04-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartable', '0005_commentviewhistory_uniqueview'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='DocumentOwnerNationalCode',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='documentflow',
            name='InboxOwnerNationalCode',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='documentflow',
            name='SenderUserNationalCode',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
