# Generated by Django 3.2.9 on 2022-01-10 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0005_degreetype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DegreeType',
        ),
    ]
