# Generated by Django 4.0.1 on 2022-02-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0015_userhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='EnterDate',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
