# Generated by Django 4.0.1 on 2022-05-02 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0032_users_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user',
        ),
    ]
