# Generated by Django 4.0.1 on 2022-07-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0044_alter_v_pagepermission_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageinformation',
            name='OrderNumber',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='ترتیب نمایش'),
        ),
    ]
