# Generated by Django 4.0.1 on 2023-01-20 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0049_team_generalmanager_team_supportmanager_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='ContractDateEndDate',
            new_name='ContractEndDate',
        ),
        migrations.RemoveField(
            model_name='users',
            name='AuthLoginDate',
        ),
        migrations.RemoveField(
            model_name='users',
            name='AuthLoginKey',
        ),
        migrations.RemoveField(
            model_name='users',
            name='DegreeType',
        ),
        migrations.RemoveField(
            model_name='users',
            name='MarriageStatus',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Marriage_Status',
        ),
        migrations.RemoveField(
            model_name='users',
            name='MilitaryStatus',
        ),
        migrations.AddField(
            model_name='users',
            name='ContractType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ContractType', to='HR.constvalue', verbose_name='نوع قرارداد'),
        ),
        migrations.AddField(
            model_name='users',
            name='IdentityCity',
            field=models.ForeignKey(default=103, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='IdentityCity', to='HR.city', verbose_name='شهر محل صدور شناسنامه'),
        ),
        migrations.AddField(
            model_name='users',
            name='IdentityRegisterDate',
            field=models.DateField(null=True, verbose_name='تاریخ صدور شناسنامه'),
        ),
        migrations.AlterField(
            model_name='users',
            name='IdentityNumber',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='شماره شناسنامه'),
        ),
        migrations.AlterField(
            model_name='users',
            name='IdentitySerialNumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='سریال شناسنامه'),
        ),
        migrations.AlterField(
            model_name='users',
            name='InsuranceNumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره بیمه'),
        ),
    ]
