# Generated by Django 4.0.1 on 2023-01-20 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0050_rename_contractdateenddate_users_contractenddate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Degree_Type',
            new_name='DegreeType',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Military_Status',
            new_name='MilitaryStatus',
        ),
    ]
