# Generated by Django 4.0.1 on 2025-02-10 13:27

import HR.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0063_teamallowedroles'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspersonnel',
            name='NationalCode',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[HR.validator.Validator.NationalCode_Validator], verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='educationhistory',
            name='PersonNationalCode',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[HR.validator.Validator.NationalCode_Validator], verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='PersonNationalCode',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[HR.validator.Validator.NationalCode_Validator], verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='PersonNationalCode',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[HR.validator.Validator.NationalCode_Validator], verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='postaladdress',
            name='PersonNationlCode',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[HR.validator.Validator.NationalCode_Validator], verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='previoususerteamrole',
            name='ManagerNationalCode',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[HR.validator.Validator.NationalCode_Validator], verbose_name='کد ملی مدیر'),
        ),
        migrations.AddField(
            model_name='previoususerteamrole',
            name='NationalCode',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[HR.validator.Validator.NationalCode_Validator], verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='team',
            name='GeneralManagerNationalCode',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[HR.validator.Validator.NationalCode_Validator], verbose_name='کد ملی مدیر عمومی'),
        ),
        migrations.AddField(
            model_name='team',
            name='SupportManagerNationalCode',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[HR.validator.Validator.NationalCode_Validator], verbose_name='کد ملی مدیر پشتیبانی'),
        ),
        migrations.AddField(
            model_name='team',
            name='TestManagerNationalCode',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[HR.validator.Validator.NationalCode_Validator], verbose_name='کد ملی مدیر تست'),
        ),
        migrations.AddField(
            model_name='userteamrole',
            name='ManagerNationalCode',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[HR.validator.Validator.NationalCode_Validator], verbose_name='کد ملی مدیر'),
        ),
        migrations.AddField(
            model_name='userteamrole',
            name='NationalCode',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[HR.validator.Validator.NationalCode_Validator], verbose_name='کد ملی'),
        ),
    ]
