# Generated by Django 4.0.1 on 2025-02-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0064_accesspersonnel_nationalcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='BirthDateMiladi',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد میلادی'),
        ),
        migrations.AddField(
            model_name='users',
            name='ContractDateMiladi',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ شروع همکاری میلادی'),
        ),
        migrations.AddField(
            model_name='users',
            name='ContractEndDateMiladi',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پایان همکاری میلادی'),
        ),
    ]
