"""
Django settings for Config project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os


BASE_DIR = Path(__file__).resolve().parent.parent
PARENT_DIR = str(BASE_DIR.parent).replace('\\','\\\\')
#sys.path.append(PARENT_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-aqigb$#bbluzl7*^r+sc6l*8f1zlrs4me1baeew9#jkv+hl&we'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.20.81','localhost','127.0.0.1','192.168.70.25']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'HR.apps.HrConfig',
    'AccessControl.apps.AccesscontrolConfig',
    'InternalAccess.apps.InternalaccessConfig',
    'django_middleware_global_request',
    'corsheaders',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_middleware_global_request.middleware.GlobalRequestMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'HR.middleware.DetectUserInfoMiddleware',
]

ROOT_URLCONF = 'Config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mssql',# 'mssql',sql_server.pyodbc
        'NAME': 'AccessControl',
        'USER': 'sa',
        'PASSWORD': 'Master123',
        'HOST': 'EIT-DJANGO-DB\\DJANGODB',
        'PORT': '',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',  # 'SQL Server Native Client 11.0'
        },
    },
    'HR': {
        'ENGINE': 'mssql',  # 'mssql',
        'NAME': 'HR',
        'USER': 'sa',
        'PASSWORD': 'Master123',
        'HOST': 'EIT-DJANGO-DB\\DJANGODB',
        'PORT': '',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',  # 'SQL Server Native Client 11.0'
        },
    },
    'EIT': {
        'ENGINE': 'mssql',  # 'mssql',
        'NAME': 'EIT',
        'USER': 'sa',
        'PASSWORD': 'Master123',
        'HOST': 'EIT-DJANGO-DB\\DJANGODB',
        'PORT': '',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',  # 'SQL Server Native Client 11.0'
        },
    },
    'VIR': {
        'ENGINE': 'mssql',  # 'mssql',
        'NAME': 'FAQ',
        'USER': 'sa',
        'PASSWORD': 'Master123',
        'HOST': 'EIT-DJANGO-DB\DJANGODB',
        'PORT': '',
        'OPTIONS': {"driver": "ODBC Driver 17 for SQL Server"},
    },
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'fa-ir'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_L10N = True

USE_TZ = True

STATIC_URL = '/static/'
if DEBUG:
    STATICFILES_DIRS = [os.path.join(BASE_DIR,"static")]
else:
    STATIC_ROOT = os.path.join(BASE_DIR, "static")
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,"media")
STATIC_URL_EIT = '/static_eit/'
STATIC_ROOT_EIT = os.path.join(BASE_DIR.parent,"EIT\static")
MEDIA_URL_HR = '/media_hr/'
MEDIA_ROOT_HR = os.path.join(BASE_DIR.parent,"HR\media")

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
DATABASE_ROUTERS = ['HR.DBRouters.router.CustomRouter',]
# in key must write app name and in value nust write database name
ROUTERS_APP_DB = {'َAccessControl':'default', 'HR':'HR','EIT':'EIT','InternalAccess':'default'}

#AUTH_USER_MODEL = 'HR.Users'
AUTHENTICATION_BACKENDS = [
    "HR.backends.LdapBackend",
]

SESSION_COOKIE_NAME = os.getcwd().split("\\")[-1] + '_sessionid'

from django_auth_ldap.config import LDAPSearch
import ldap

AUTH_LDAP_SERVER_URI = "ldap://192.168.20.22:389"
AUTH_LDAP_BIND_DN = 'bpms'
AUTH_LDAP_BIND_PASSWORD = 'Wsxedc@123'
AUTH_LDAP_USER_SEARCH = LDAPSearch("DC=eit,DC=local", ldap.SCOPE_SUBTREE, "(&(objectClass=*)(sAMAccountName=%(user)s))")


REDIS_HOST = 'localhost'
REDIS_PORT = 6379

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"https://192.168.20.81$",
    r"http://192.168.20.81$",

]

CORS_ALLOW_ALL_ORIGINS = True
CURRENT_APP_PORT = "13000"
ACCESSCONTROL_IP_PORT = "http://192.168.20.81:13000"
APP_MODE = "production"
if os.path.exists(os.path.join(BASE_DIR,"Config/local_settings.py")):
    from .local_settings import *
    APP_MODE = "development"
    print("start app in development mode")
else:
    print("your app is production mode")
