# Generated by Django 3.2.9 on 2021-12-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccessControl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='Logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='تصویر'),
        ),
    ]
