# Generated by Django 3.2.9 on 2021-12-13 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '__first__'),
        ('AccessControl', '0002_system_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'verbose_name': 'اپلیکیشن', 'verbose_name_plural': 'اپلیکیشن ها'},
        ),
        migrations.AlterModelOptions(
            name='apppermissiontype',
            options={'verbose_name': 'نوع دسترسی', 'verbose_name_plural': 'نوع های دسترسی '},
        ),
        migrations.AlterModelOptions(
            name='appurl',
            options={'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس ها'},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name': '  دسترسی ', 'verbose_name_plural': 'دسترسی ها '},
        ),
        migrations.AlterModelOptions(
            name='permissiongroup',
            options={'verbose_name': 'گروه دسترسی', 'verbose_name_plural': 'گروه های دسترسی '},
        ),
        migrations.AlterModelOptions(
            name='permissionvariable',
            options={'verbose_name': 'متغیر', 'verbose_name_plural': 'متغیر ها'},
        ),
        migrations.AlterModelOptions(
            name='system',
            options={'verbose_name': 'سیستم', 'verbose_name_plural': 'سیستم ها'},
        ),
        migrations.AlterModelOptions(
            name='userrolegrouppermission',
            options={'verbose_name': 'دسته بندی دسترسی ', 'verbose_name_plural': 'دسته بندی دسترسی ها '},
        ),
        migrations.AlterField(
            model_name='userrolegrouppermission',
            name='OwnerPermissionGroup',
            field=models.ForeignKey(blank=True, db_column='OwnerPermissionGroup', null=True, on_delete=django.db.models.deletion.CASCADE, to='AccessControl.permissiongroup', verbose_name='تیم'),
        ),
        migrations.AlterField(
            model_name='userrolegrouppermission',
            name='OwnerPermissionRole',
            field=models.ForeignKey(blank=True, db_column='OwnerPermissionRole', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.role', verbose_name='سمت'),
        ),
        migrations.AlterField(
            model_name='userrolegrouppermission',
            name='OwnerPermissionUser',
            field=models.ForeignKey(blank=True, db_column='OwnerPermissionUser', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.users', verbose_name='کاربر'),
        ),
    ]
