# Generated by Django 3.2.9 on 2021-12-13 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccessControl', '0003_auto_20211213_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrolegrouppermission',
            name='OwnerPermissionGroup',
        ),
        migrations.DeleteModel(
            name='PermissionGroup',
        ),
    ]
