# Generated by Django 3.2.9 on 2021-12-13 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccessControl', '0004_auto_20211213_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, verbose_name='شرح')),
            ],
            options={
                'verbose_name': 'گروه دسترسی',
                'verbose_name_plural': 'گروه های دسترسی ',
            },
        ),
        migrations.AddField(
            model_name='userrolegrouppermission',
            name='OwnerPermissionGroup',
            field=models.ForeignKey(blank=True, db_column='OwnerPermissionGroup', null=True, on_delete=django.db.models.deletion.CASCADE, to='AccessControl.permissiongroup', verbose_name='تیم'),
        ),
    ]
