# Generated by Django 3.2.9 on 2021-12-13 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '__first__'),
        ('AccessControl', '0005_auto_20211213_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccessControl.permissiongroup', verbose_name='گروه')),
                ('User', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='HR.users', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گروه کاربری ',
                'verbose_name_plural': 'گروه های کاربری ',
            },
        ),
    ]
