# Generated by Django 3.2.9 on 2021-12-25 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccessControl', '0006_groupuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrolegrouppermission',
            name='OwnerPermissionGroup',
            field=models.ForeignKey(blank=True, db_column='OwnerPermissionGroup', null=True, on_delete=django.db.models.deletion.CASCADE, to='AccessControl.permissiongroup', verbose_name='گروه'),
        ),
        migrations.CreateModel(
            name='RelatedPermissionAPPURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppURL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccessControl.appurl', verbose_name='آدرس')),
                ('Permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccessControl.permission', verbose_name='نام دسترسی')),
            ],
            options={
                'verbose_name': 'ارتباط آدرس با دسترسی ',
                'verbose_name_plural': 'آدرس ها و دسترسی های مرتبط ',
            },
        ),
    ]
