# Generated by Django 3.2.9 on 2021-12-25 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '__first__'),
        ('AccessControl', '0007_auto_20211225_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'verbose_name': 'برنامه', 'verbose_name_plural': 'برنامه ها'},
        ),
        migrations.AlterField(
            model_name='appurl',
            name='AppCode',
            field=models.ForeignKey(db_column='AppCode', on_delete=django.db.models.deletion.CASCADE, to='AccessControl.app', verbose_name='کد اپلیکیشن'),
        ),
        migrations.CreateModel(
            name='PermissionVariableValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VariableValue', models.CharField(max_length=200, verbose_name='مقدار متغیر')),
                ('App', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccessControl.app', verbose_name='نام برنامه')),
                ('OwnerVariableGroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AccessControl.permissiongroup', verbose_name='گروه')),
                ('OwnerVariableRole', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.role', verbose_name='سمت')),
                ('OwnerVariableUser', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.users', verbose_name='کاربر')),
                ('PermissionVariable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccessControl.permissionvariable', verbose_name='نام تغیر')),
            ],
            options={
                'verbose_name': 'مقدار متغیر',
                'verbose_name_plural': 'مقادیر متغیرها',
            },
        ),
    ]
