# Generated by Django 3.2.9 on 2021-12-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccessControl', '0008_auto_20211225_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='Title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
    ]
