# Generated by Django 3.2.9 on 2021-12-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccessControl', '0009_alter_app_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionvariablevalue',
            name='VariableValue',
            field=models.CharField(max_length=300, verbose_name='مقدار متغیر'),
        ),
    ]
