# Generated by Django 3.2.9 on 2022-01-03 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '__first__'),
        ('AccessControl', '0010_alter_permissionvariablevalue_variablevalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccessControl.app', verbose_name='نام برنامه')),
                ('TeamCode', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='HR.team', verbose_name='نام برنامه')),
            ],
            options={
                'verbose_name': 'تیم برنامه ',
                'verbose_name_plural': 'تیم های برنامه ها ',
            },
        ),
    ]
