# Generated by Django 3.2.9 on 2022-01-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccessControl', '0011_appteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='AppLabel',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='نام لاتین برنامه'),
        ),
    ]
