# Generated by Django 4.0.1 on 2022-02-07 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccessControl', '0012_app_applabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IPAddress', models.GenericIPAddressField(verbose_name='ادرس')),
                ('DNSName', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام سرور')),
                ('ServerName', models.CharField(max_length=200, verbose_name='نام ')),
            ],
            options={
                'verbose_name': 'سرور',
                'verbose_name_plural': 'سرورها',
            },
        ),
        migrations.AddField(
            model_name='system',
            name='Server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AccessControl.server', verbose_name='نام سرور'),
        ),
    ]
