# Generated by Django 4.0.1 on 2022-04-30 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HR', '__first__'),
        ('AccessControl', '0013_server_system_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='SystemCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='App_SystemCode', to='AccessControl.system', verbose_name='کدسیستم'),
        ),
        migrations.CreateModel(
            name='T1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='HR.team', verbose_name='نام برنامه')),
                ('u', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام برنامه')),
            ],
        ),
    ]
