# Generated by Django 4.0.1 on 2022-04-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccessControl', '0014_alter_app_systemcode_t1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t1',
            name='t',
            field=models.CharField(max_length=20, verbose_name='نام برنامه'),
        ),
        migrations.AlterField(
            model_name='t1',
            name='u',
            field=models.CharField(max_length=20, verbose_name='نام برنامه'),
        ),
    ]
