# Generated by Django 4.0.1 on 2022-04-30 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AccessControl', '0015_alter_t1_t_alter_t1_u'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t1',
            name='t',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='HR.team', verbose_name='نام برنامه'),
        ),
        migrations.AlterField(
            model_name='t1',
            name='u',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام برنامه'),
        ),
    ]
