# Generated by Django 4.0.1 on 2022-04-30 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccessControl', '0016_alter_t1_t_alter_t1_u'),
    ]

    operations = [
        migrations.DeleteModel(
            name='T1',
        ),
    ]
