# Generated by Django 4.0.1 on 2022-04-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccessControl', '0017_delete_t1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appteam',
            name='TeamCode',
            field=models.CharField(max_length=5, verbose_name='نام برنامه'),
        ),
        migrations.AlterField(
            model_name='groupuser',
            name='User',
            field=models.CharField(max_length=100, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='permissionvariablevalue',
            name='OwnerVariableRole',
            field=models.IntegerField(null=True, verbose_name='سمت'),
        ),
        migrations.AlterField(
            model_name='permissionvariablevalue',
            name='OwnerVariableUser',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='userrolegrouppermission',
            name='OwnerPermissionRole',
            field=models.IntegerField(blank=True, db_column='OwnerPermissionRole', null=True, verbose_name='سمت'),
        ),
        migrations.AlterField(
            model_name='userrolegrouppermission',
            name='OwnerPermissionUser',
            field=models.CharField(blank=True, db_column='OwnerPermissionUser', max_length=100, null=True, verbose_name='کاربر'),
        ),
    ]
