# Generated by Django 4.0.1 on 2022-05-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccessControl', '0018_alter_appteam_teamcode_alter_groupuser_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appurl',
            name='IsPublic',
            field=models.BooleanField(default=False, null=True, verbose_name='عمومی بودن برنامه برای همه کاربران'),
        ),
    ]
