# Generated by Django 4.0.1 on 2022-05-30 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '__first__'),
        ('AccessControl', '0019_appurl_ispublic'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableValueRelated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ValueTitle', models.CharField(max_length=200, verbose_name='مقدار متغیر')),
            ],
            options={
                'verbose_name': 'مقدار ',
                'verbose_name_plural': 'مقادیر ',
            },
        ),
        migrations.RemoveField(
            model_name='appurl',
            name='IsPublic',
        ),
        migrations.AlterField(
            model_name='app',
            name='SystemCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccessControl.system', verbose_name='کدسیستم'),
        ),
        migrations.AlterField(
            model_name='appteam',
            name='TeamCode',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='HR.team', verbose_name='نام برنامه'),
        ),
        migrations.AlterField(
            model_name='groupuser',
            name='User',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='HR.users', verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='PermissionType',
            field=models.CharField(choices=[('V', 'مجوز مشاهده'), ('E', 'مجوز ویرایش'), ('A', 'دسترسی کامل'), ('U', 'دسترسی ادرس'), ('D', 'دسترسی پورتال')], max_length=1, verbose_name='نوع مجوز'),
        ),
        migrations.AlterField(
            model_name='permissionvariablevalue',
            name='OwnerVariableRole',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.role', verbose_name='سمت'),
        ),
        migrations.AlterField(
            model_name='permissionvariablevalue',
            name='OwnerVariableUser',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.users', verbose_name='کاربر'),
        ),
        migrations.RemoveField(
            model_name='permissionvariablevalue',
            name='VariableValue',
        ),
        migrations.AlterField(
            model_name='userrolegrouppermission',
            name='OwnerPermissionRole',
            field=models.ForeignKey(blank=True, db_column='OwnerPermissionRole', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.role', verbose_name='سمت'),
        ),
        migrations.AlterField(
            model_name='userrolegrouppermission',
            name='OwnerPermissionUser',
            field=models.ForeignKey(blank=True, db_column='OwnerPermissionUser', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.users', verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='permissionvariablevalue',
            name='VariableValue',
            field=models.ManyToManyField(to='AccessControl.VariableValueRelated', verbose_name='مقدار متغیر'),
        ),
    ]
