# Generated by Django 4.0.1 on 2022-05-30 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccessControl', '0021_remove_permissionvariablevalue_variablevalue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionvariablevalue',
            name='VariableValue',
        ),
        migrations.AddField(
            model_name='variablevaluerelated',
            name='VariableValue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AccessControl.permissionvariablevalue', verbose_name=' متغیر'),
        ),
    ]
