# Generated by Erfan Rezaee on {{datetime}}

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('{{app_name}}', '{{last_migration}}'),
    ]

    with open("{{sql_path}}", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="{{reverse_sql}}"
        )
    ]
