# Generated by Django 4.0.1 on 2022-02-06 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        #('AccessControl', '__first__'),
        # ('HR', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500, verbose_name='نام دسته بندی')),
                ('Icon', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='ایکون')),
                ('OrderNumber', models.IntegerField(blank=True, null=True, verbose_name='ترتیب')),
                ('Parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SystemCategoryParents', to='Systems.systemcategory', verbose_name='نام دسته بندی پدر')),
                ('UserName', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SystemCategoryUserNames', to='HR.users', verbose_name='نام کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='SystemCategoryURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                #('AppURL', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SystemCategoryURLAppURLs', to='AccessControl.appurl', verbose_name='مسیر برنامه')),
                ('SystemCategory', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SystemCategoryURLSystemCategorys', to='Systems.systemcategory', verbose_name='مسیر برنامه')),
            ],
        ),
    ]
