# Generated by Django 4.0.1 on 2022-05-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Systems', '0002_alter_systemcategoryurl_systemcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemcategoryurl',
            name='AppURL',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='مسیر برنامه'),
        ),
    ]
