# Generated by Django 4.0.1 on 2022-05-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Systems', '0003_systemcategoryurl_appurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemcategoryurl',
            name='AppURL',
            field=models.BigIntegerField(null=True),
        ),
    ]
