# Generated by Django 4.0.1 on 2022-11-13 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Systems', '0004_alter_systemcategoryurl_appurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemcategory',
            name='Parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SystemCategoryParents', to='Systems.systemcategory', verbose_name='نام دسته بندی پدر'),
        ),
        migrations.AlterField(
            model_name='systemcategory',
            name='UserName',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='نام کاربر'),
        ),
        migrations.AlterField(
            model_name='systemcategoryurl',
            name='SystemCategory',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SystemCategoryURLSystemCategorys', to='Systems.systemcategory', verbose_name='دسته بندی برنامه'),
        ),
    ]
