# Generated by Django 4.0.1 on 2022-11-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Systems', '0006_alter_systemcategory_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemcategory',
            name='UserName',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='نام کاربر'),
        ),
    ]
