CREATE TABLE [dbo].[AccessControl_app](
	[Code] [nvarchar](6) NOT NULL,
	[Title] [nvarchar](100) NOT NULL,
	[SystemCode_id] [nvarchar](3) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
