CREATE TABLE [dbo].[HR_rolegroup](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[RoleGroup] [nvarchar](50) NOT NULL,
	[RoleGroupName] [nvarchar](100) NULL,
	[RoleID_id] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
