CREATE TABLE [dbo].[HR_fieldofstudy](
	[id] [bigint] NOT NULL,
	[Title] [nvarchar](150) NOT NULL,
 CONSTRAINT [PK__HR_field__3213E83FA016913F] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
