CREATE TABLE [dbo].[Cartable_document](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[AppDocId] [int] NOT NULL,
	[Priority] [nvarchar](100) NOT NULL,
	[DocState] [nvarchar](100) NOT NULL,
	[AppURLId_id] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
