CREATE TABLE [dbo].[HR_province](
	[id] [bigint] NOT NULL,
	[ProvinceTitle] [nvarchar](50) NOT NULL,
	[AbbreviationCode] [nvarchar](2) NULL,
	[PhoneCode] [int] NULL,
 CONSTRAINT [PK__HR_provi__3213E83F09A289BF] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ__HR_provi__C1314ED00D4273A9] UNIQUE NONCLUSTERED 
(
	[ProvinceTitle] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
