CREATE TABLE [dbo].[HR_accesspersonnel](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[UserName_id] [varchar](100) NOT NULL,
	[NationalCode] [nvarchar](10) NULL,
 CONSTRAINT [PK__HR_acces__3213E83F3FE62382] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
