CREATE TABLE [dbo].[HR_emailaddress](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[Email] [nvarchar](254) NOT NULL,
	[Title] [nvarchar](100) NULL,
	[Person_id] [varchar](100) NULL,
	[IsDefault] [bit] NOT NULL,
	[PersonNationalCode] [nvarchar](10) NULL,
 CONSTRAINT [PK__HR_email__3213E83F37A5CB59] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
