CREATE TABLE [dbo].[Sheet1$](
	[ردیف] [float] NULL,
	[شماره پرسنلي] [nvarchar](255) NULL,
	[نام] [nvarchar](255) NULL,
	[نام‌خانوادگي] [nvarchar](255) NULL,
	[نام کاربری] [nvarchar](255) NULL,
	[نام پدر] [nvarchar](255) NULL,
	[شماره شناسنامه] [nvarchar](255) NULL,
	[سريال شناسنامه] [nvarchar](255) NULL,
	[محل صدور شناسنامه] [nvarchar](255) NULL,
	[تاريخ صدور شناسنامه] [nvarchar](255) NULL,
	[تاريخ تولد] [nvarchar](255) NULL,
	[محل تولد] [nvarchar](255) NULL,
	[شماره ملي] [nvarchar](255) NULL,
	[تعداد اولاد] [nvarchar](255) NULL,
	[آدرس] [nvarchar](255) NULL,
	[تلفن منزل] [nvarchar](255) NULL,
	[تلفن ضروري] [nvarchar](255) NULL,
	[تلفن همراه] [nvarchar](255) NULL,
	[کد پستي] [nvarchar](255) NULL,
	[ايميل] [nvarchar](255) NULL,
	[تاريخ استخدام] [nvarchar](255) NULL,
	[تاريخ ورود به خدمت] [nvarchar](255) NULL,
	[تاريخ ترك خدمت] [nvarchar](255) NULL,
	[محل اخذ مدرك] [nvarchar](255) NULL,
	[نوع دانشگاه] [nvarchar](255) NULL,
	[معدل] [nvarchar](255) NULL,
	[شماره بيمه] [nvarchar](255) NULL,
	[جنسيت] [nvarchar](255) NULL,
	[وضعيت اشتغال] [nvarchar](255) NULL,
	[محل خدمت] [nvarchar](255) NULL,
	[مليت] [nvarchar](255) NULL,
	[مقطع تحصيلي] [nvarchar](255) NULL,
	[وضعيت نظام‌وظيفه] [nvarchar](255) NULL,
	[وضعيت تاهل] [nvarchar](255) NULL,
	[نوع استخدام] [nvarchar](255) NULL,
	[دين] [nvarchar](255) NULL,
	[استان صدور شناسنامه] [nvarchar](255) NULL,
	[شهر محل صدور شناسنامه] [nvarchar](255) NULL,
	[رشته تحصيلي] [nvarchar](255) NULL,
	[قسمت كاري] [nvarchar](255) NULL,
	[پست رسمي] [nvarchar](255) NULL,
	[دپارتمان رسمي] [nvarchar](255) NULL
) ON [PRIMARY]
