CREATE TABLE [dbo].[HR_citydistrict](
	[id] [bigint] NOT NULL,
	[DistrictTitle] [nvarchar](50) NOT NULL,
	[City_id] [int] NOT NULL,
 CONSTRAINT [PK__HR_cityd__3213E83FD27FBCDE] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
