# Generated by Django 3.2.9 on 2021-12-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LevelName', models.CharField(max_length=20, verbose_name='نام سطح')),
            ],
            options={
                'verbose_name': 'سطح',
                'verbose_name_plural': 'سطوح',
                'db_table': 'RoleLevel',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='BirthDate',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AddField(
            model_name='users',
            name='ContractDate',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ استخدام'),
        ),
        migrations.AddField(
            model_name='users',
            name='DegreeType',
            field=models.IntegerField(blank=True, choices=[(1, 'زیر دیپلم'), (2, 'دیپلم'), (3, 'کاردانی'), (4, 'کارشناسی'), (5, 'فوق کارشناسی'), (6, 'دکترا')], null=True, verbose_name='مقطع تحصیلی'),
        ),
        migrations.AddField(
            model_name='users',
            name='FieldOfStudy',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='رشته تحصیلی'),
        ),
        # Oldmigrations.AlterField(
        #     model_name='userteamrole',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
    ]
