# Generated by Django 3.2.9 on 2022-01-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0002_auto_20211215_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='HasLevel',
            field=models.BooleanField(default=False, verbose_name='دارای سطح'),
        ),
        migrations.AddField(
            model_name='role',
            name='HasSuperior',
            field=models.BooleanField(default=False, verbose_name='ارشد دارد'),
        ),
        migrations.AlterField(
            model_name='userteamrole',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
