# Generated by Django 3.2.9 on 2022-01-09 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0003_auto_20220108_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='userteamrole',
            name='LevelId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.rolelevel', verbose_name='سطح'),
        ),
        migrations.AddField(
            model_name='userteamrole',
            name='Superior',
            field=models.BooleanField(default=False, verbose_name='ارشد'),
        ),
    ]
