# Generated by Django 3.2.9 on 2022-01-11 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0006_delete_degreetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='V_UserTeamRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Superior', models.BooleanField(default=False, verbose_name='ارشد')),
                ('StartDate', models.CharField(max_length=10, verbose_name='تاریخ شروع')),
                ('EndDate', models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ پایان')),
            ],
            options={
                'verbose_name': 'اطلاعات پرسنل',
                'verbose_name_plural': 'اطلاعات همه ی پرسنل',
                'db_table': 'V_UserTeamRole',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='userteamrole',
            name='ManagerUserName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ManagerUserNames', to='HR.users', verbose_name='نام مدیر'),
        ),
        migrations.AlterField(
            model_name='userteamrole',
            name='UserName',
            field=models.ForeignKey(db_column='UserName', on_delete=django.db.models.deletion.CASCADE, related_name='UserNames', to='HR.users', verbose_name='نام کاربری'),
        ),
    ]
