# Generated by Django 4.0.1 on 2022-02-01 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0008_accesspersonnel_changerole_organizationchartrole_organizationchartteamrole_rolegroup_rolegrouptarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CityTitle', models.CharField(max_length=100, verbose_name='شهر')),
                ('PhoneCode', models.IntegerField(blank=True, null=True, verbose_name='پیش شماره شهرستان')),
                ('IsCapital', models.BooleanField(default=False, verbose_name='مرکز استان است؟')),
                ('CityCode', models.CharField(blank=True, max_length=4, null=True, verbose_name='کد شهر')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهرها',
            },
        ),
        migrations.CreateModel(
            name='CityDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DistrictTitle', models.CharField(max_length=50, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'ناحیه شهری',
                'verbose_name_plural': 'نواحی شهری',
            },
        ),
        migrations.CreateModel(
            name='ConstValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Caption', models.CharField(max_length=50, verbose_name='عنوان')),
                ('Code', models.CharField(max_length=100, verbose_name='کد')),
                ('IsActive', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('OrderNumber', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='شماره ترتیب')),
                ('ConstValue', models.IntegerField(blank=True, null=True, verbose_name='مقدار مربوطه')),
                ('Parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.constvalue', verbose_name='شناسه پدر')),
            ],
            options={
                'verbose_name': 'مقدار ثابت',
                'verbose_name_plural': 'مقادیر ثابت',
                'ordering': ['Parent_id', 'OrderNumber'],
            },
        ),
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150, verbose_name='رشته')),
            ],
            options={
                'verbose_name': 'رشته تحصیلی',
                'verbose_name_plural': 'رشته های تحصیلی',
                'ordering': ('Title',),
            },
        ),
        migrations.CreateModel(
            name='MilitaryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MilitaryService', models.CharField(max_length=300, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'وضعیت پایان خدمت',
                'verbose_name_plural': 'وضعیت های پایان خدمت',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProvinceTitle', models.CharField(max_length=50, unique=True, verbose_name='استان')),
                ('AbbreviationCode', models.CharField(blank=True, max_length=2, null=True, verbose_name='کد استان')),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان ها',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150, verbose_name='نام دانشگاه')),
                ('UniversityType', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'دولتی'), (2, 'دانشگاه آزاد اسلامی'), (3, 'غیرانتفاعی'), (4, 'علمی و کاربردی'), (5, 'پیام نور'), (6, 'مجازی')], null=True, verbose_name='نوع دانشگاه')),
            ],
            options={
                'verbose_name': 'دانشگاه',
                'verbose_name_plural': 'دانشگاه ها',
            },
        ),
        migrations.RemoveField(
            model_name='users',
            name='FieldOfStudy',
        ),
        migrations.AddField(
            model_name='users',
            name='About',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='درباره من'),
        ),
        migrations.AddField(
            model_name='users',
            name='Address',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='users',
            name='CVFile',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='فایل رزومه'),
        ),
        migrations.AddField(
            model_name='users',
            name='FirstNameEnglish',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='نام لاتین'),
        ),
        migrations.AddField(
            model_name='users',
            name='Gender',
            field=models.BooleanField(default=False, verbose_name='جنسیت'),
        ),
        migrations.AddField(
            model_name='users',
            name='LastNameEnglish',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام خانوادگی لاتین'),
        ),
        migrations.AddField(
            model_name='users',
            name='MarriageStatus',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'مجرد'), (2, 'متاهل'), (3, 'جدا شده'), (4, 'فوت شده')], default=1, null=True, verbose_name='وضعیت تاهل'),
        ),
        migrations.AddField(
            model_name='users',
            name='NationalCode',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='users',
            name='NumberOfChildren',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='تعداد فرزند'),
        ),
        migrations.AlterField(
            model_name='users',
            name='DegreeType',
            field=models.IntegerField(blank=True, choices=[(0, 'بی سواد'), (1, 'ابتدایی'), (2, 'دبیرستان'), (3, 'دیپلم'), (4, 'کاردانی'), (5, 'کارشناسی'), (6, 'کارشناسی ارشد'), (7, 'دکتری')], null=True, verbose_name='آخرین مقطع تحصیلی'),
        ),
        migrations.CreateModel(
            name='Tendency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150, verbose_name='گرایش')),
                ('FieldOfStudy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.fieldofstudy', verbose_name='گرایش تحصیلی')),
            ],
            options={
                'verbose_name': 'گرایش تحصیلی',
                'verbose_name_plural': 'گرایش های تحصیلی',
            },
        ),
        migrations.CreateModel(
            name='PostalAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان')),
                ('AddressText', models.CharField(blank=True, max_length=500, null=True, verbose_name='آدرس')),
                ('No', models.CharField(blank=True, max_length=20, null=True, verbose_name='پلاک')),
                ('UnitNo', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='شماره واحد')),
                ('PostalCode', models.IntegerField(blank=True, null=True, verbose_name='کد پستی')),
                ('CityDistrict', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HR.citydistrict', verbose_name='منطقه')),
                ('Person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.users', verbose_name='فرد')),
            ],
            options={
                'verbose_name': 'آدرس پستی',
                'verbose_name_plural': 'آدرس های پستی',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TelNumber', models.BigIntegerField(help_text=' شماره ثابت بدون داخلی وارد شود. (مثلا : 87654321) شماره موبایل بدون صفر وارد شود مثلاً 9121234567', verbose_name='شماره تماس')),
                ('TelType2', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'تلفن همراه'), (2, 'منزل'), (3, 'محل کار'), (4, 'ضروری')], null=True, verbose_name='نوع')),
                ('Title', models.CharField(blank=True, max_length=50, null=True, verbose_name='توضیحات')),
                ('Person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.users', verbose_name='فرد')),
                ('TelType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HR.constvalue', verbose_name='نوع')),
            ],
            options={
                'verbose_name': 'شماره تماس',
                'verbose_name_plural': 'شماره های تماس',
            },
        ),
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, verbose_name='ادرس ایمیل')),
                ('Title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان')),
                ('Person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.users', verbose_name='فرد')),
            ],
            options={
                'verbose_name': 'آدرس پست الکترونیکی',
                'verbose_name_plural': 'آدرس های پست الکترونیکی',
            },
        ),
        migrations.CreateModel(
            name='EducationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DegreeType', models.IntegerField(blank=True, choices=[(1, 'زیر دیپلم'), (2, 'دیپلم'), (3, 'کاردانی'), (4, 'کارشناسی'), (5, 'فوق کارشناسی'), (6, 'دکترا')], null=True, verbose_name='مقطع تحصیلی')),
                ('StartDate', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('EndDate', models.DateField(blank=True, null=True, verbose_name='تاریخ خاتمه')),
                ('StartYear', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سال ورود')),
                ('EndYear', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سال فراغت از تحصیل')),
                ('IsStudent', models.BooleanField(default=False, verbose_name='دانشجو است؟')),
                ('GPA', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='معدل')),
                ('EducationTendency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HR.tendency', verbose_name='رشته')),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.users', verbose_name='پرسنل')),
                ('University', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HR.university', verbose_name='دانشگاه محل تحصیل')),
            ],
            options={
                'verbose_name': 'سابقه تحصیلی',
                'verbose_name_plural': 'سوابق تحصیلی',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='LivingAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HR.postaladdress', verbose_name='آدرس محل سکونت'),
        ),
        migrations.AddField(
            model_name='users',
            name='MilitaryStatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HR.militaryservice', verbose_name='وضعیت خدمت'),
        ),
    ]
