# Generated by Django 4.0.1 on 2022-02-01 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0009_city_citydistrict_constvalue_fieldofstudy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='Province',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.SET_DEFAULT, to='HR.province', verbose_name='استان'),
        ),
    ]
