# Generated by Django 4.0.1 on 2022-02-01 07:23

import HR.validator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0010_city_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='citydistrict',
            name='City',
            field=models.ForeignKey(default=103, on_delete=django.db.models.deletion.CASCADE, to='HR.city', verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='City',
            field=models.ForeignKey(blank=True, default=103, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HR.city', verbose_name='پیش شماره شهرستان'),
        ),
        migrations.AddField(
            model_name='postaladdress',
            name='City',
            field=models.ForeignKey(default=103, on_delete=django.db.models.deletion.SET_DEFAULT, to='HR.city', verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='university',
            name='UniversityCity',
            field=models.ForeignKey(default=103, on_delete=django.db.models.deletion.SET_DEFAULT, to='HR.city', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='educationhistory',
            name='EndYear',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[HR.validator.Validator.YearNumber], verbose_name='سال فراغت از تحصیل'),
        ),
        migrations.AlterField(
            model_name='educationhistory',
            name='StartYear',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[HR.validator.Validator.YearNumber], verbose_name='سال ورود'),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='PostalCode',
            field=models.IntegerField(blank=True, null=True, validators=[HR.validator.Validator.PostalCode], verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='users',
            name='NationalCode',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[HR.validator.Validator.NationalCode_Validator], verbose_name='کد ملی'),
        ),
    ]
