# Generated by Django 4.0.1 on 2022-02-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0012_users_date_joined_users_email_users_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='AuthLoginDate',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='AuthLoginKey',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
