# Generated by Django 4.0.1 on 2022-02-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0013_users_authlogindate_users_authloginkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='AuthLoginKey',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
