# Generated by Django 4.0.1 on 2022-02-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0014_alter_users_authloginkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=300)),
                ('AuthLoginKey', models.CharField(max_length=300, null=True)),
                ('RequestDate', models.DateTimeField(default=None)),
                ('EnterDate', models.DateTimeField(auto_now=True, null=True)),
                ('RequestUrl', models.CharField(max_length=300, null=True)),
                ('EnterUrl', models.CharField(max_length=300, null=True)),
                ('IP', models.GenericIPAddressField(null=True)),
                ('UserAgent', models.CharField(max_length=300, null=True)),
                ('ChangedUserInfo', models.BooleanField(default=None, null=True)),
            ],
        ),
    ]
