# Generated by Django 4.0.1 on 2022-02-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0016_alter_userhistory_enterdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='AppName',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
