# Generated by Django 4.0.1 on 2022-03-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0017_userhistory_appname'),
    ]

    operations = [
        migrations.CreateModel(
            name='V_HR_RoleTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Superior', models.BooleanField(default=False, verbose_name='وضعیت فعلی ارشد')),
                ('SuperiorTarget', models.BooleanField(default=False, verbose_name='وضعیت فعلی ارشد')),
                ('Education', models.BooleanField(default=True, verbose_name='آموزش نیاز دارد؟')),
                ('Educator', models.CharField(blank=True, max_length=100, null=True, verbose_name='آموزش دهنده')),
                ('Evaluation', models.BooleanField(default=True, verbose_name='ارزیابی نیاز دارد؟')),
                ('Assessor', models.CharField(blank=True, max_length=100, null=True, verbose_name='ارزیابی کننده')),
                ('PmChange', models.BooleanField(default=True, verbose_name='تغیرات PM؟')),
                ('ITChange', models.BooleanField(default=True, verbose_name='تغیرات IT؟')),
                ('RequestType', models.IntegerField(verbose_name='نوع درخواست')),
            ],
            options={
                'verbose_name': 'تغییر جایگاه',
                'verbose_name_plural': 'تغییرات جایگاه',
                'db_table': 'V_HR_RoleTarget',
                'managed': False,
            },
        ),
    ]
