# Generated by Django 4.0.1 on 2022-03-13 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0019_v_roleteam_alter_users_authlogindate'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationhistory',
            name='Degree_Type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HR.constvalue', verbose_name=' مقطع تحصیلی'),
        ),
        migrations.AddField(
            model_name='university',
            name='University_Type',
            field=models.ForeignKey(blank=True, limit_choices_to={'IsActive': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='HR.constvalue', verbose_name='نوع دانشگاه'),
        ),
        migrations.AddField(
            model_name='users',
            name='Degree_Type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HR.constvalue', verbose_name='آخرین مقطع تحصیلی'),
        ),
        migrations.AddField(
            model_name='users',
            name='Marriage_Status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='UsersMarriageStatus', to='HR.constvalue', verbose_name='وضعیت تاهل'),
        ),
        migrations.AddField(
            model_name='users',
            name='Military_Status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='UsersMilitaryStatus', to='HR.constvalue', verbose_name='وضعیت خدمت'),
        ),
    ]
