# Generated by Django 4.0.1 on 2022-04-13 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0023_remove_phonenumber_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationhistory',
            name='Degree_Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HR.constvalue', verbose_name=' مقطع تحصیلی'),
        ),
        migrations.AlterField(
            model_name='educationhistory',
            name='EducationTendency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HR.tendency', verbose_name='رشته'),
        ),
    ]
