# Generated by Django 4.0.1 on 2022-04-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('HR', '0024_alter_educationhistory_degree_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
