# Generated by Django 4.0.1 on 2022-04-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('HR', '0026_alter_users_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='groups',
        ),
        migrations.AddField(
            model_name='users',
            name='custom_groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
