# Generated by Django 4.0.1 on 2022-05-02 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0030_users_is_active_users_is_speruser_users_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='is_speruser',
            new_name='is_superuser',
        ),
    ]
