# Generated by Django 4.0.1 on 2022-06-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0035_payment_v_worktime_virtualusers_worktime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Address',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='آدرس'),
        ),
    ]
