# Generated by Django 4.0.1 on 2022-07-01 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0038_v_pagepermission_pageinformation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagepermission',
            name='PageName',
        ),
    ]
