# Generated by Django 4.0.1 on 2022-07-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0041_pageinformation_colorset_pageinformation_englishname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageinformation',
            name='ColorSet',
            field=models.CharField(max_length=30, verbose_name='رنگ آیکون صفحه'),
        ),
        migrations.AlterField(
            model_name='pageinformation',
            name='EnglishName',
            field=models.CharField(max_length=30, verbose_name='نام لاتین صفحه'),
        ),
        migrations.AlterField(
            model_name='pageinformation',
            name='IconName',
            field=models.CharField(max_length=30, verbose_name='آیکون صفحه'),
        ),
    ]
