# Generated by Django 4.0.1 on 2022-07-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0042_alter_pageinformation_colorset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageinformation',
            name='ShowDetail',
            field=models.BooleanField(default=False, verbose_name='جزییات نمایش داده شود؟'),
        ),
    ]
