# Generated by Django 4.0.1 on 2022-07-02 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0043_pageinformation_showdetail'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='v_pagepermission',
            table='V_PagePermission',
        ),
    ]
