# Generated by Django 4.0.1 on 2022-08-31 04:32

import HR.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0045_pageinformation_ordernumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='TelType2',
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='PostalCode',
            field=models.BigIntegerField(blank=True, null=True, validators=[HR.validator.Validator.PostalCode], verbose_name='کد پستی'),
        ),
    ]
