# Generated by Django 4.0.1 on 2022-09-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0046_remove_phonenumber_teltype2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='LivingAddress',
        ),
        migrations.RemoveField(
            model_name='users',
            name='MilitaryStatus',
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='IsDefault',
            field=models.BooleanField(default=False, verbose_name='پیش فرض'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='IsDefault',
            field=models.BooleanField(default=False, verbose_name='پیش فرض'),
        ),
        migrations.AddField(
            model_name='postaladdress',
            name='IsDefault',
            field=models.BooleanField(default=False, verbose_name='پیش فرض'),
        ),
        migrations.AddField(
            model_name='users',
            name='ContractDateEndDate',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پایان همکاری'),
        ),
        migrations.DeleteModel(
            name='MilitaryService',
        ),
    ]
