# Generated by Django 4.0.1 on 2022-09-06 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0047_remove_users_livingaddress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilitaryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MilitaryService', models.CharField(max_length=300, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'وضعیت پایان خدمت',
                'verbose_name_plural': 'وضعیت های پایان خدمت',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='LivingAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HR.postaladdress', verbose_name='آدرس محل سکونت'),
        ),
        migrations.AddField(
            model_name='users',
            name='MilitaryStatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HR.militaryservice', verbose_name='وضعیت خدمت'),
        ),
    ]
