# Generated by Django 4.0.1 on 2022-11-06 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0048_militaryservice_users_livingaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='GeneralManager',
            field=models.ForeignKey(help_text='مدیر عمومی می تواند، مدیر پروژه یا مدیر اداری، یا  مدیر اداری یا کلا هر مدیری باشد', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TeamGeneralManager', to='HR.users', verbose_name='مدیر عمومی'),
        ),
        migrations.AddField(
            model_name='team',
            name='SupportManager',
            field=models.ForeignKey(help_text='برای تیم های عملیانی مشخص می شود و برای غیر عملیاتی ها نال است', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TeamSupportManager', to='HR.users', verbose_name='مدیر پشتیبانی'),
        ),
        migrations.AddField(
            model_name='team',
            name='TestManager',
            field=models.ForeignKey(help_text='برای تیم های عملیانی مشخص می شود و برای غیر عملیاتی ها نال است', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TeamTestManager', to='HR.users', verbose_name='مدیر تست'),
        ),
    ]
