# Generated by Django 4.0.1 on 2023-01-20 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0053_userfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='UserStatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserStatus', to='HR.constvalue', verbose_name='وضعیت کاربر'),
        ),
    ]
