# Generated by Django 4.0.1 on 2023-01-20 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0054_users_userstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='MarriageStatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='UsersMarriageStatus', to='HR.constvalue', verbose_name='وضعیت تاهل'),
        ),
        migrations.AddField(
            model_name='users',
            name='IsActive',
            field=models.BooleanField(default=True, verbose_name='کاربر فعال است؟'),
        ),
    ]
