# Generated by Django 4.0.1 on 2023-09-28 10:50

import HR.validator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0055_users_marriagestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YearNumber', models.IntegerField(verbose_name='سال')),
                ('Payment', models.BigIntegerField(blank=True, help_text='این مبلغ خالص دریافتی کاربر است', null=True, verbose_name='خالص دریافتی')),
                ('TotalPayment', models.BigIntegerField(blank=True, help_text='کل پرداختی ها شامل حقوق پایه، اضافه کار، پاداش و ...', null=True, verbose_name='حقوق ناخالص')),
                ('OtherPayment', models.BigIntegerField(blank=True, help_text='مثلا سوبسید ناهار تایم یا بیمه تکمیلی که شرکت برای این فرد پرداخت می کند', null=True, verbose_name='سایر هزینه های کارفرما')),
                ('PaymentCost', models.BigIntegerField(blank=True, help_text='بهای تمام شده فرد شامل کل حقوق دریافتی + بیمه کارفرما + سایر هزینه های پرداختی کارفرما است', null=True, verbose_name='بهای تمام شده این فرد')),
                ('BasePayment', models.BigIntegerField(blank=True, help_text='حقوق پایه یعنی مبلغ ناخالص قرارداد فرد', null=True, verbose_name='پایه حقوق')),
                ('OverTimePayment', models.BigIntegerField(blank=True, help_text='مبلغی که فرد بابت اضافه کار در ماه دریافت کرده است', null=True, verbose_name='هزینه اضافه کاری')),
                ('OverTime', models.IntegerField(blank=True, help_text='میزان اضافه کاری فرد بر حسب دقیقه', null=True, verbose_name='ساعت اضافه کاری')),
                ('Reward', models.BigIntegerField(blank=True, help_text='مبلغی که فرد به عنوان پاداش در آن ماه دریافت کرده است', null=True, verbose_name='مبلغ پاداش ماهانه')),
                ('MonthNumber', models.IntegerField(verbose_name='ماه')),
            ],
            options={
                'verbose_name': 'میانگین حقوق سالانه',
                'verbose_name_plural': 'میانگین حقوق سالانه',
                'db_table': 'V_Payment_Average',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentAverageYearly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YearNumber', models.IntegerField(verbose_name='سال')),
                ('Payment', models.BigIntegerField(blank=True, help_text='این مبلغ خالص دریافتی کاربر است', null=True, verbose_name='خالص دریافتی')),
                ('TotalPayment', models.BigIntegerField(blank=True, help_text='کل پرداختی ها شامل حقوق پایه، اضافه کار، پاداش و ...', null=True, verbose_name='حقوق ناخالص')),
                ('OtherPayment', models.BigIntegerField(blank=True, help_text='مثلا سوبسید ناهار تایم یا بیمه تکمیلی که شرکت برای این فرد پرداخت می کند', null=True, verbose_name='سایر هزینه های کارفرما')),
                ('PaymentCost', models.BigIntegerField(blank=True, help_text='بهای تمام شده فرد شامل کل حقوق دریافتی + بیمه کارفرما + سایر هزینه های پرداختی کارفرما است', null=True, verbose_name='بهای تمام شده این فرد')),
                ('BasePayment', models.BigIntegerField(blank=True, help_text='حقوق پایه یعنی مبلغ ناخالص قرارداد فرد', null=True, verbose_name='پایه حقوق')),
                ('OverTimePayment', models.BigIntegerField(blank=True, help_text='مبلغی که فرد بابت اضافه کار در ماه دریافت کرده است', null=True, verbose_name='هزینه اضافه کاری')),
                ('OverTime', models.IntegerField(blank=True, help_text='میزان اضافه کاری فرد بر حسب دقیقه', null=True, verbose_name='ساعت اضافه کاری')),
                ('Reward', models.BigIntegerField(blank=True, help_text='مبلغی که فرد به عنوان پاداش در آن ماه دریافت کرده است', null=True, verbose_name='مبلغ پاداش ماهانه')),
            ],
            options={
                'verbose_name': 'میانگین حقوق سالانه',
                'verbose_name_plural': 'میانگین حقوق سالانه',
                'db_table': 'V_Payment_Average_Yearly',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentRoleAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YearNumber', models.IntegerField(verbose_name='سال')),
                ('Payment', models.BigIntegerField(blank=True, help_text='این مبلغ خالص دریافتی کاربر است', null=True, verbose_name='خالص دریافتی')),
                ('TotalPayment', models.BigIntegerField(blank=True, help_text='کل پرداختی ها شامل حقوق پایه، اضافه کار، پاداش و ...', null=True, verbose_name='حقوق ناخالص')),
                ('OtherPayment', models.BigIntegerField(blank=True, help_text='مثلا سوبسید ناهار تایم یا بیمه تکمیلی که شرکت برای این فرد پرداخت می کند', null=True, verbose_name='سایر هزینه های کارفرما')),
                ('PaymentCost', models.BigIntegerField(blank=True, help_text='بهای تمام شده فرد شامل کل حقوق دریافتی + بیمه کارفرما + سایر هزینه های پرداختی کارفرما است', null=True, verbose_name='بهای تمام شده این فرد')),
                ('BasePayment', models.BigIntegerField(blank=True, help_text='حقوق پایه یعنی مبلغ ناخالص قرارداد فرد', null=True, verbose_name='پایه حقوق')),
                ('OverTimePayment', models.BigIntegerField(blank=True, help_text='مبلغی که فرد بابت اضافه کار در ماه دریافت کرده است', null=True, verbose_name='هزینه اضافه کاری')),
                ('OverTime', models.IntegerField(blank=True, help_text='میزان اضافه کاری فرد بر حسب دقیقه', null=True, verbose_name='ساعت اضافه کاری')),
                ('Reward', models.BigIntegerField(blank=True, help_text='مبلغی که فرد به عنوان پاداش در آن ماه دریافت کرده است', null=True, verbose_name='مبلغ پاداش ماهانه')),
                ('MonthNumber', models.IntegerField(verbose_name='ماه')),
            ],
            options={
                'verbose_name': 'میانگین حقوق سالانه به تفکیک سمت',
                'verbose_name_plural': 'میانگین حقوق سالانه به تفکیک سمت',
                'db_table': 'V_Payment_Role_Average',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentRoleAverageYearly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YearNumber', models.IntegerField(verbose_name='سال')),
                ('Payment', models.BigIntegerField(blank=True, help_text='این مبلغ خالص دریافتی کاربر است', null=True, verbose_name='خالص دریافتی')),
                ('TotalPayment', models.BigIntegerField(blank=True, help_text='کل پرداختی ها شامل حقوق پایه، اضافه کار، پاداش و ...', null=True, verbose_name='حقوق ناخالص')),
                ('OtherPayment', models.BigIntegerField(blank=True, help_text='مثلا سوبسید ناهار تایم یا بیمه تکمیلی که شرکت برای این فرد پرداخت می کند', null=True, verbose_name='سایر هزینه های کارفرما')),
                ('PaymentCost', models.BigIntegerField(blank=True, help_text='بهای تمام شده فرد شامل کل حقوق دریافتی + بیمه کارفرما + سایر هزینه های پرداختی کارفرما است', null=True, verbose_name='بهای تمام شده این فرد')),
                ('BasePayment', models.BigIntegerField(blank=True, help_text='حقوق پایه یعنی مبلغ ناخالص قرارداد فرد', null=True, verbose_name='پایه حقوق')),
                ('OverTimePayment', models.BigIntegerField(blank=True, help_text='مبلغی که فرد بابت اضافه کار در ماه دریافت کرده است', null=True, verbose_name='هزینه اضافه کاری')),
                ('OverTime', models.IntegerField(blank=True, help_text='میزان اضافه کاری فرد بر حسب دقیقه', null=True, verbose_name='ساعت اضافه کاری')),
                ('Reward', models.BigIntegerField(blank=True, help_text='مبلغی که فرد به عنوان پاداش در آن ماه دریافت کرده است', null=True, verbose_name='مبلغ پاداش ماهانه')),
            ],
            options={
                'verbose_name': 'میانگین حقوق سالانه به تفکیک سمت',
                'verbose_name_plural': 'میانگین حقوق سالانه به تفکیک سمت',
                'db_table': 'V_Payment_Role_Average_Yearly',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentYearly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YearNumber', models.IntegerField(verbose_name='سال')),
                ('Payment', models.BigIntegerField(blank=True, help_text='این مبلغ خالص دریافتی کاربر است', null=True, verbose_name='خالص دریافتی')),
                ('TotalPayment', models.BigIntegerField(blank=True, help_text='کل پرداختی ها شامل حقوق پایه، اضافه کار، پاداش و ...', null=True, verbose_name='حقوق ناخالص')),
                ('OtherPayment', models.BigIntegerField(blank=True, help_text='مثلا سوبسید ناهار تایم یا بیمه تکمیلی که شرکت برای این فرد پرداخت می کند', null=True, verbose_name='سایر هزینه های کارفرما')),
                ('PaymentCost', models.BigIntegerField(blank=True, help_text='بهای تمام شده فرد شامل کل حقوق دریافتی + بیمه کارفرما + سایر هزینه های پرداختی کارفرما است', null=True, verbose_name='بهای تمام شده این فرد')),
                ('BasePayment', models.BigIntegerField(blank=True, help_text='حقوق پایه یعنی مبلغ ناخالص قرارداد فرد', null=True, verbose_name='پایه حقوق')),
                ('OverTimePayment', models.BigIntegerField(blank=True, help_text='مبلغی که فرد بابت اضافه کار در ماه دریافت کرده است', null=True, verbose_name='هزینه اضافه کاری')),
                ('OverTime', models.IntegerField(blank=True, help_text='میزان اضافه کاری فرد بر حسب دقیقه', null=True, verbose_name='ساعت اضافه کاری')),
                ('Reward', models.BigIntegerField(blank=True, help_text='مبلغی که فرد به عنوان پاداش در آن ماه دریافت کرده است', null=True, verbose_name='مبلغ پاداش ماهانه')),
                ('PersonnelCode', models.CharField(max_length=10, verbose_name='کدملی')),
            ],
            options={
                'verbose_name': 'حقوق',
                'verbose_name_plural': 'حقوق های پرسنل',
                'db_table': 'V_Payment_Yearly',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YearNumber', models.IntegerField(verbose_name='سال')),
                ('MonthNumber', models.IntegerField(verbose_name='ماه')),
                ('ItemValue', models.BigIntegerField(verbose_name='مقدار مربوطه')),
                ('Code', models.CharField(max_length=200, verbose_name='کد مورد مربوطه')),
                ('PersonnelCode', models.CharField(max_length=10, verbose_name='کدملی')),
            ],
            options={
                'db_table': 'V_UserSlip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserSlipAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YearNumber', models.IntegerField(verbose_name='سال')),
                ('MonthNumber', models.IntegerField(verbose_name='ماه')),
                ('ItemValue', models.BigIntegerField(verbose_name='مقدار مربوطه')),
                ('Code', models.CharField(max_length=200, verbose_name='کد مورد مربوطه')),
            ],
            options={
                'db_table': 'V_UserSlip_Average',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='MilitaryService',
        ),
        migrations.AddField(
            model_name='team',
            name='IsActive',
            field=models.BooleanField(default=True, verbose_name='آیا تیم فعال است؟'),
        ),

        migrations.AlterField(
            model_name='city',
            name='CityTitle',
            field=models.CharField(max_length=100, verbose_name='نام شهر'),
        ),
        migrations.AlterField(
            model_name='city',
            name='Province',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.SET_DEFAULT, to='HR.province', verbose_name='استان مربوطه'),
        ),
        migrations.AlterField(
            model_name='citydistrict',
            name='City',
            field=models.ForeignKey(default=103, on_delete=django.db.models.deletion.CASCADE, to='HR.city', verbose_name='شهر مربوطه'),
        ),
        migrations.AlterField(
            model_name='citydistrict',
            name='DistrictTitle',
            field=models.CharField(max_length=50, verbose_name='نام منطقه'),
        ),
        migrations.AlterField(
            model_name='educationhistory',
            name='DegreeType',
            field=models.IntegerField(blank=True, choices=[(1, 'زیر دیپلم'), (2, 'دیپلم'), (3, 'کاردانی'), (4, 'کارشناسی'), (5, 'فوق کارشناسی'), (6, 'دکترا')], help_text='دیگر از این فیلد برای نوع مقطع مدرک تحصیلی استفاده نمی کنیم.', null=True, verbose_name='مقطع تحصیلی'),
        ),
        migrations.AlterField(
            model_name='educationhistory',
            name='EducationTendency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HR.tendency', verbose_name='گرایش تحصیلی'),
        ),
        migrations.AlterField(
            model_name='educationhistory',
            name='EndYear',
            field=models.PositiveSmallIntegerField(blank=True, help_text='تاریخ شمسی', null=True, validators=[HR.validator.Validator.YearNumber], verbose_name='سال فراغت از تحصیل'),
        ),
        migrations.AlterField(
            model_name='educationhistory',
            name='Person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_history', to='HR.users', verbose_name='پرسنل'),
        ),
        migrations.AlterField(
            model_name='educationhistory',
            name='StartYear',
            field=models.PositiveSmallIntegerField(blank=True, help_text='تاریخ شمسی', null=True, validators=[HR.validator.Validator.YearNumber], verbose_name='سال ورود'),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='IsDefault',
            field=models.BooleanField(default=False, verbose_name='آدرس ایمیل پیشفرض است؟'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='Person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_number', to='HR.users', verbose_name='فرد'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='Province',
            field=models.ForeignKey(blank=True, default=103, help_text='این فیلد زمانی پر می شود که تلفن خط ثابت باشد', null=True, on_delete=django.db.models.deletion.SET_NULL, to='HR.province', verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='TelType',
            field=models.ForeignKey(help_text='منظور از نوع این است که می تواند، محل زندگی، همراه، ضروری و... باشد', on_delete=django.db.models.deletion.PROTECT, to='HR.constvalue', verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='City',
            field=models.ForeignKey(default=103, on_delete=django.db.models.deletion.SET_DEFAULT, to='HR.city', verbose_name='شهر محل زندگی'),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='IsDefault',
            field=models.BooleanField(default=False, verbose_name='آدرس پیش فرض است؟'),
        ),
        migrations.AlterField(
            model_name='province',
            name='PhoneCode',
            field=models.IntegerField(blank=True, null=True, verbose_name='پیش شماره استان'),
        ),
        migrations.AlterField(
            model_name='province',
            name='ProvinceTitle',
            field=models.CharField(max_length=50, unique=True, verbose_name='نام استان'),
        ),
        migrations.AlterField(
            model_name='university',
            name='UniversityCity',
            field=models.ForeignKey(default=103, on_delete=django.db.models.deletion.SET_DEFAULT, to='HR.city', verbose_name='شهر محل دانشگاه'),
        ),
        migrations.AlterField(
            model_name='university',
            name='UniversityType',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'دولتی'), (2, 'دانشگاه آزاد اسلامی'), (3, 'غیرانتفاعی'), (4, 'علمی و کاربردی'), (5, 'پیام نور'), (6, 'مجازی')], help_text='دیگر از این فیلد برای تعیین نوع دانشگاه استفاده نمی کنیم', null=True, verbose_name='نوع دانشگاه'),
        ),
        migrations.AlterField(
            model_name='users',
            name='BirthCity',
            field=models.ForeignKey(default=103, on_delete=django.db.models.deletion.SET_DEFAULT, to='HR.city', verbose_name='شهر محل تولد'),
        ),
        migrations.AlterField(
            model_name='users',
            name='ContractDate',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ شروع همکاری'),
        ),
        migrations.DeleteModel(
            name='UserFile',
        ),
    ]
