# Generated by Django 4.0.1 on 2025-01-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0059_v_teaminformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='V_KeyMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=250, verbose_name='نام')),
                ('UserAlone', models.CharField(max_length=250, verbose_name='نام')),
                ('FirstName', models.CharField(max_length=250, verbose_name='نام')),
                ('LastName', models.CharField(max_length=250, verbose_name='نام خانوادگی')),
                ('TeamCode', models.CharField(max_length=3, verbose_name='کد تیم')),
                ('RoleName', models.CharField(max_length=100, verbose_name='سمت')),
                ('Superior', models.BooleanField(verbose_name='ارشد')),
            ],
            options={
                'verbose_name': 'فرد کلیدی',
                'verbose_name_plural': 'افراد کلیدی',
                'db_table': 'KeyMembers',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='v_teaminformation',
            table='TeamInformation',
        ),
    ]
