# Generated by Django 4.0.1 on 2025-01-24 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0062_newrolerequest_setteamallowedrolerequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamAllowedRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AllowedRoleCount', models.PositiveSmallIntegerField(default='100', verbose_name='تعداد مجاز')),
                ('Comment', models.CharField(max_length=500, verbose_name='توضیحات')),
                ('RoleId', models.ForeignKey(db_column='RoleId', on_delete=django.db.models.deletion.CASCADE, to='HR.role', verbose_name='شناسه مربوطه')),
                ('SetTeamAllowedRoleRequest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HR.setteamallowedrolerequest', verbose_name='شناسه درخواست مربوطه')),
                ('TeamCode', models.ForeignKey(db_column='TeamCode', on_delete=django.db.models.deletion.CASCADE, to='HR.team', verbose_name='کد تیم مربوطه')),
            ],
            options={
                'verbose_name': 'سمت های مجاز تیم',
                'verbose_name_plural': 'سمت های مجاز تیم ها',
                'unique_together': {('TeamCode', 'RoleId')},
            },
        ),
    ]
