# Generated by Django 4.0.1 on 2025-02-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0065_users_birthdatemiladi_users_contractdatemiladi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='BirthDate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='users',
            name='ContractDate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ شروع همکاری'),
        ),
        migrations.AlterField(
            model_name='users',
            name='ContractEndDate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ پایان همکاری'),
        ),
    ]
