# Generated by Django 4.0.1 on 2025-03-01 13:58

import HR.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0066_alter_users_birthdate_alter_users_contractdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postaladdress',
            old_name='PersonNationlCode',
            new_name='PersonNationalCode',
        ),
        migrations.AddField(
            model_name='organizationchartteamrole',
            name='ManagerNationalCode',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[HR.validator.Validator.NationalCode_Validator], verbose_name='کد ملی مدیر'),
        ),
    ]
