# Generated by Django 5.0.12 on 2025-04-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0068_roleinformation_delete_virtualusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleinformation',
            name='Title',
            field=models.CharField(db_column='Title', max_length=50, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='setteamallowedrolerequest',
            name='DocId',
            field=models.IntegerField(blank=True, null=True, verbose_name='شناسه سند'),
        ),
        migrations.AddField(
            model_name='setteamallowedrolerequest',
            name='StatusCode',
            field=models.CharField(choices=[('DRAFTR', 'پیش نویس'), ('MANREV', 'بررسی مدیر'), ('CTOREV', 'بررسی مدیر عامل'), ('FINSUC', 'خاتمه - تایید'), ('FINREJ', 'خاتمه - رد'), ('FAILED', 'خطا')], default='DRAFTR', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='setteamallowedrolerequest',
            name='CTODate',
            field=models.DateField(null=True, verbose_name='تاریخ اظهار نظر مدیرعامل'),
        ),
        migrations.AlterField(
            model_name='setteamallowedrolerequest',
            name='CTOOpinion',
            field=models.BooleanField(help_text='در صورت موافقت مقدار یک و در غیر این صورت صفر می باشد', null=True, verbose_name='نظر مدیر عامل'),
        ),
        migrations.AlterField(
            model_name='setteamallowedrolerequest',
            name='ManagerOpinion',
            field=models.BooleanField(help_text='در صورت موافقت مقدار یک و در غیر این صورت صفر می باشد', null=True, verbose_name='نظر مدیر درخواست دهنده'),
        ),
        migrations.AlterField(
            model_name='teamallowedroles',
            name='AllowedRoleCount',
            field=models.PositiveSmallIntegerField(default='100', null=True, verbose_name='تعداد مجاز'),
        ),
    ]
