# Generated by Django 5.0.12 on 2025-04-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0069_roleinformation_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newrolerequest',
            name='ConditionsText',
            field=models.CharField(max_length=1000, null=True, verbose_name='این سمت چه شرایط احرازی دارد ؟'),
        ),
        migrations.AddField(
            model_name='newrolerequest',
            name='DutiesText',
            field=models.CharField(max_length=1000, null=True, verbose_name='این سمت چه شرایح شغلی دارد ؟'),
        ),
        migrations.AddField(
            model_name='newrolerequest',
            name='StatusCode',
            field=models.CharField(choices=[('DRAFTR', 'پیش نویس'), ('MANREV', 'بررسی مدیر'), ('CTOREV', 'بررسی مدیر عامل'), ('FINSUC', 'خاتمه - تایید'), ('FINREJ', 'خاتمه - رد'), ('FAILED', 'خطا')], default='DRAFTR', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='newrolerequest',
            name='CTODate',
            field=models.DateField(null=True, verbose_name='تاریخ اظهار نظر مدیرعامل'),
        ),
    ]
