# Generated by Django 2.1.15 on 2021-12-01 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('RoleId', models.IntegerField(primary_key=True, serialize=False, verbose_name='کد سمت')),
                ('RoleName', models.CharField(max_length=100, verbose_name='نام سمت')),
            ],
            options={
                'verbose_name': 'سمت',
                'verbose_name_plural': 'سمت ها',
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('TeamCode', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='کدتیم')),
                ('TeamName', models.CharField(max_length=100, verbose_name='نام تیم')),
                ('ActiveInService', models.BooleanField(default=True, verbose_name=' کتاب')),
                ('ActiveInEvaluation', models.BooleanField(default=True, verbose_name='ارزیابی')),
            ],
            options={
                'verbose_name': 'تیم',
                'verbose_name_plural': 'تیم ها',
                'db_table': 'Team',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserName', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='نام کاربری')),
                ('FirstName', models.CharField(max_length=200, verbose_name='نام')),
                ('LastName', models.CharField(max_length=200, verbose_name='نام خانوادگی')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='UserTeamRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.CharField(max_length=10, verbose_name='تاریخ شروع')),
                ('EndDate', models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ پایان')),
                ('RoleId', models.ForeignKey(db_column='RoleId', on_delete=django.db.models.deletion.CASCADE, to='HR.Role', verbose_name='کد سمت')),
                ('TeamCode', models.ForeignKey(db_column='TeamCode', on_delete=django.db.models.deletion.CASCADE, to='HR.Team', verbose_name='کدتیم')),
                ('UserName', models.ForeignKey(db_column='UserName', on_delete=django.db.models.deletion.CASCADE, to='HR.Users', verbose_name='نام کاربری')),
            ],
            options={
                'verbose_name': 'اطلاعات پرسنل',
                'verbose_name_plural': 'اطلاعات همه ی پرسنل',
                'db_table': 'UserTeamRole',
            },
        ),
    ]
