# Generated by Django 3.2.9 on 2022-01-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0004_auto_20220109_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DegreeType', models.CharField(max_length=300, verbose_name='مقاطع تحصیلی')),
            ],
            options={
                'verbose_name': 'مقطع',
                'verbose_name_plural': 'مقاطع',
            },
        ),
    ]
