# Generated by Django 3.2.9 on 2022-01-18 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0007_auto_20220111_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationChartRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LevelId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OrganizationChartRoleRoleLevels', to='HR.rolelevel', verbose_name='سطح ')),
                ('RoleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrganizationChartRoleRoleIDs', to='HR.role', verbose_name='سمت')),
            ],
            options={
                'verbose_name': 'سمت و سطح',
                'verbose_name_plural': 'سمت ها و سطح ها',
            },
        ),
        migrations.CreateModel(
            name='RoleGroupTargetException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleGroup', models.CharField(max_length=100, verbose_name='گروه مبدا')),
                ('RoleGroupTarget', models.CharField(max_length=100, verbose_name='گروه مقصد')),
            ],
            options={
                'verbose_name': 'گروه سمت',
                'verbose_name_plural': 'گروه های سمت ها',
            },
        ),
        migrations.CreateModel(
            name='RoleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleGroup', models.CharField(max_length=50, verbose_name='گروه')),
                ('RoleGroupName', models.CharField(blank=True, max_length=100, null=True, verbose_name=' نام گروه')),
                ('RoleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RoleGroupRoleIDs', to='HR.role', verbose_name='سمت فعلی')),
            ],
            options={
                'verbose_name': 'گروه سمت',
                'verbose_name_plural': 'گروه های سمت ها',
            },
        ),
        migrations.CreateModel(
            name='OrganizationChartTeamRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleCount', models.IntegerField(blank=True, null=True, verbose_name='ظرفیت سمت')),
                ('ManagerUserName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OrganizationChartTeamRoleManagerUserNames', to='HR.users', verbose_name='نام مدیر')),
                ('OrganizationChartRole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.organizationchartrole', verbose_name='مدیر تیم و سمت')),
                ('TeamCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrganizationChartTeamRoleTeamCodes', to='HR.team', verbose_name='نام تیم')),
            ],
            options={
                'verbose_name': 'سمت  تیم',
                'verbose_name_plural': 'سمت های تیم های عملیاتی',
            },
        ),
        migrations.CreateModel(
            name='ChangeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Superior', models.BooleanField(default=False, verbose_name='وضعیت فعلی ارشد')),
                ('SuperiorTarget', models.BooleanField(default=False, verbose_name='وضعیت جدید ارشد')),
                ('Education', models.BooleanField(default=True, verbose_name='آموزش نیاز دارد؟')),
                ('Educator', models.CharField(blank=True, max_length=100, null=True, verbose_name='آموزش دهنده')),
                ('Evaluation', models.BooleanField(default=True, verbose_name='ارزیابی نیاز دارد؟')),
                ('Assessor', models.CharField(blank=True, max_length=100, null=True, verbose_name='ارزیابی کننده')),
                ('RequestGap', models.IntegerField(blank=True, null=True, verbose_name='مدت زمان')),
                ('Assessor2', models.CharField(blank=True, max_length=100, null=True, verbose_name='ارزیابی کننده دوم')),
                ('ReEvaluation', models.BooleanField(default=True, verbose_name='ارزیابی  دوم نیاز دارد؟')),
                ('PmChange', models.BooleanField(default=True, verbose_name='تغیرات PM؟')),
                ('ITChange', models.BooleanField(default=True, verbose_name='تغیرات IT؟')),
                ('LevelId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ChangeRoleRoleLevels', to='HR.rolelevel', verbose_name='سطح فعلی')),
                ('LevelIdTarget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ChangeRoleLevelIdTargets', to='HR.rolelevel', verbose_name='سطح جدید')),
                ('RoleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ChangeRoleRoleIDs', to='HR.role', verbose_name='سمت فعلی')),
                ('RoleIdTarget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ChangeRoleRoleIdTargets', to='HR.role', verbose_name='سمت جدید')),
            ],
            options={
                'verbose_name': 'اطلاعات تغییر سمت',
                'verbose_name_plural': 'اطلاعات تغییر سمت ها',
            },
        ),
        migrations.CreateModel(
            name='AccessPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AccessPersonnelUserNames', to='HR.users', verbose_name='نام کاربری')),
            ],
            options={
                'verbose_name': 'دسترسی انتخاب  سمت',
                'verbose_name_plural': 'دسترسی های انتخاب همه سمت ها',
            },
        ),
    ]
