# Generated by Django 4.0.1 on 2022-04-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0020_educationhistory_degree_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='PhoneCode',
        ),
        migrations.AddField(
            model_name='province',
            name='PhoneCode',
            field=models.IntegerField(blank=True, null=True, verbose_name='پیش شماره شهرستان'),
        ),
    ]
