# Generated by Django 4.0.1 on 2022-04-13 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0021_remove_city_phonecode_province_phonecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='Province',
            field=models.ForeignKey(blank=True, default=103, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HR.province', verbose_name='پیش شماره شهرستان'),
        ),
    ]
