# Generated by Django 4.0.1 on 2022-04-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0022_phonenumber_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='City',
        ),
    ]
