# Generated by Django 4.0.1 on 2022-04-20 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0027_remove_users_groups_users_custom_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='custom_groups',
        ),
    ]
