# Generated by Django 4.0.1 on 2022-06-12 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0034_customusersimplelazyobject_remove_users_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YearNumber', models.IntegerField(verbose_name='سال')),
                ('Payment', models.BigIntegerField(blank=True, null=True, verbose_name='حقوق')),
                ('MonthNo', models.IntegerField(verbose_name='ماه')),
                ('PersonnelCode', models.CharField(max_length=10, verbose_name='کدملی')),
                ('BasePayment', models.BigIntegerField(blank=True, null=True, verbose_name='پایه حقوق')),
            ],
            options={
                'verbose_name': 'حقوق',
                'verbose_name_plural': 'حقوق های پرسنل',
                'db_table': 'V_Payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V_WorkTime',
            fields=[
                ('YearNo', models.IntegerField(verbose_name='سال')),
                ('WorkHours', models.CharField(max_length=10, verbose_name='ساعت حضوری')),
                ('RemoteHours', models.CharField(max_length=10, verbose_name='ساعت دورکاری')),
                ('RemoteDays', models.IntegerField(verbose_name='روز دورکاری')),
                ('OverTime', models.CharField(max_length=10, verbose_name='اضافه کار')),
                ('DeductionTime', models.CharField(max_length=10, verbose_name='کسر کار')),
                ('OffTimeHourly', models.CharField(max_length=10, verbose_name='ساعت مرخصی')),
                ('OffTimeDaily', models.IntegerField(verbose_name='روز مرخصی')),
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'اطلاعات چارگون',
                'verbose_name_plural': 'اطلاعات چارگون',
                'db_table': 'V_WorkTime',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VirtualUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'کاربر برنامه ها',
                'verbose_name_plural': 'کاربران برنامه ها',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('YearNo', models.IntegerField(verbose_name='سال')),
                ('MonthNo', models.IntegerField(verbose_name='ماه')),
                ('PersonnelCode', models.CharField(max_length=10, verbose_name='کدملی')),
                ('WorkHours', models.CharField(max_length=10, verbose_name='ساعت حضوری')),
                ('RemoteHours', models.CharField(max_length=10, verbose_name='ساعت دورکاری')),
                ('RemoteDays', models.IntegerField(verbose_name='روز دورکاری')),
                ('OverTime', models.CharField(max_length=10, verbose_name='اضافه کار')),
                ('DeductionTime', models.CharField(max_length=10, verbose_name='کسر کار')),
                ('OffTimeHourly', models.CharField(max_length=10, verbose_name='ساعت مرخصی')),
                ('OffTimeDaily', models.IntegerField(verbose_name='روز مرخصی')),
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'اطلاعات چارگون',
                'verbose_name_plural': 'اطلاعات چارگون',
                'db_table': 'WorkTime',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreviousUserTeamRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Superior', models.BooleanField(default=False, verbose_name='ارشد')),
                ('StartDate', models.CharField(max_length=10, verbose_name='تاریخ شروع')),
                ('EndDate', models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ پایان')),
                ('LevelId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.rolelevel', verbose_name='سطح')),
            ],
            options={
                'verbose_name': 'اطلاعات پرسنل',
                'verbose_name_plural': 'اطلاعات همه ی پرسنل',
                'db_table': 'PreviousUserTeamRole',
            },
        ),
        migrations.RemoveField(
            model_name='users',
            name='Address',
        ),
        migrations.AddField(
            model_name='users',
            name='BirthCity',
            field=models.ForeignKey(default=103, on_delete=django.db.models.deletion.SET_DEFAULT, to='HR.city', verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='users',
            name='FatherName',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام پدر'),
        ),
        migrations.AddField(
            model_name='users',
            name='IdentityNumber',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره شناسنامه'),
        ),
        migrations.AddField(
            model_name='users',
            name='IdentitySerialNumber',
            field=models.IntegerField(blank=True, null=True, verbose_name='سریال شناسنامه'),
        ),
        migrations.AddField(
            model_name='users',
            name='InsuranceNumber',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره بیمه'),
        ),
        migrations.AddField(
            model_name='users',
            name='Religion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='UsersReligion', to='HR.constvalue', verbose_name='دین'),
        ),
        migrations.AlterField(
            model_name='userteamrole',
            name='ManagerUserName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserTeamRoleManagerUserNames', to='HR.users', verbose_name='نام مدیر'),
        ),
        migrations.AlterField(
            model_name='userteamrole',
            name='UserName',
            field=models.ForeignKey(db_column='UserName', on_delete=django.db.models.deletion.CASCADE, related_name='UserTeamRoleUserNames', to='HR.users', verbose_name='نام کاربری'),
        ),
        migrations.AddField(
            model_name='previoususerteamrole',
            name='ManagerUserName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ManagerUserNames', to='HR.users', verbose_name='نام مدیر'),
        ),
        migrations.AddField(
            model_name='previoususerteamrole',
            name='RoleId',
            field=models.ForeignKey(db_column='RoleId', on_delete=django.db.models.deletion.CASCADE, to='HR.role', verbose_name='کد سمت'),
        ),
        migrations.AddField(
            model_name='previoususerteamrole',
            name='TeamCode',
            field=models.ForeignKey(db_column='TeamCode', on_delete=django.db.models.deletion.CASCADE, to='HR.team', verbose_name='کدتیم'),
        ),
        migrations.AddField(
            model_name='previoususerteamrole',
            name='UserName',
            field=models.ForeignKey(db_column='UserName', on_delete=django.db.models.deletion.CASCADE, related_name='UserNames', to='HR.users', verbose_name='نام کاربری'),
        ),
    ]
