# Generated by Django 4.0.1 on 2022-06-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0036_users_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PageName', models.CharField(max_length=30, verbose_name='نام صفحه')),
                ('GroupId', models.PositiveIntegerField(verbose_name='شناسه گروه')),
                ('Editable', models.BooleanField(default=False, verbose_name='قابل ویرایش')),
            ],
            options={
                'verbose_name': 'دسترسی صفحه',
                'verbose_name_plural': 'دسترسی های صفحات',
            },
        ),
    ]
