# Generated by Django 4.0.1 on 2022-07-01 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0037_pagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='V_PagePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PageName', models.CharField(max_length=30, verbose_name='نام صفحه')),
                ('GroupId', models.PositiveIntegerField(verbose_name='شناسه گروه')),
                ('Editable', models.BooleanField(default=False, verbose_name='قابل ویرایش')),
            ],
            options={
                'verbose_name': 'دسترسی صفحه',
                'verbose_name_plural': 'دسترسی های صفحات',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PageInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PageName', models.CharField(max_length=30, verbose_name='نام صفحه')),
            ],
            options={
                'verbose_name': 'اطلاعات صفحه',
                'verbose_name_plural': 'اطلاعات صفحات',
            },
        ),
        migrations.AlterField(
            model_name='pagepermission',
            name='PageName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.pageinformation', verbose_name='نام صفحه'),
        ),
    ]
