# Generated by Django 4.0.1 on 2022-07-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0040_pagepermission_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageinformation',
            name='ColorSet',
            field=models.CharField(max_length=30, null=True, verbose_name='رنگ آیکون صفحه'),
        ),
        migrations.AddField(
            model_name='pageinformation',
            name='EnglishName',
            field=models.CharField(max_length=30, null=True, verbose_name='نام لاتین صفحه'),
        ),
        migrations.AddField(
            model_name='pageinformation',
            name='IconName',
            field=models.CharField(max_length=30, null=True, verbose_name='آیکون صفحه'),
        ),
    ]
