# Generated by Django 4.0.1 on 2023-01-20 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0052_remove_users_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DescriptionText', models.CharField(max_length=2000, verbose_name='توضیحات')),
                ('UserFile', models.FileField(upload_to='', verbose_name='فایل')),
                ('FileType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.constvalue', verbose_name='نوع فایل')),
            ],
            options={
                'verbose_name': 'فایل کاربر',
                'verbose_name_plural': 'فایلهای کاربران',
            },
        ),
    ]
