# Generated by Django 4.0.1 on 2024-01-26 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0057_v_alluserlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='LastBuilding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UsersBuilding', to='HR.constvalue'),
        ),
        migrations.AddField(
            model_name='users',
            name='LastFloor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UsersFloor', to='HR.constvalue'),
        ),
    ]
