# Generated by Django 4.0.1 on 2024-08-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0058_users_lastbuilding_users_lastfloor'),
    ]

    operations = [
        migrations.CreateModel(
            name='V_TeamInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeamCode', models.CharField(max_length=3, verbose_name='کد تیم')),
                ('TeamName', models.CharField(max_length=100, verbose_name='نام تیم')),
                ('TeamDesc', models.CharField(max_length=4000, verbose_name='توضیحات تیم')),
                ('ShortDesc', models.CharField(max_length=1000, verbose_name='توضیحات مختصر تیم')),
                ('TeamCount', models.PositiveSmallIntegerField(verbose_name='تعداد نفرات تیم')),
            ],
            options={
                'verbose_name': 'اطلاعات تیم',
                'verbose_name_plural': 'اطلاعات تیم ها',
                'db_table': 'V_TeamInformation',
                'managed': False,
            },
        ),
    ]
