# Generated by Django 4.0.1 on 2025-01-24 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0060_v_keymembers_alter_v_teaminformation_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationhistory',
            name='DegreeType',
        ),
        migrations.RemoveField(
            model_name='university',
            name='UniversityType',
        ),
    ]
