# Generated by Django 5.0.12 on 2025-05-15 10:56

import HR.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0071_roletype_newrolerequest_docid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='V_HR_RoleManager',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('ManagerNationalCode', models.CharField(blank=True, max_length=10, null=True, validators=[HR.validator.Validator.NationalCode_Validator], verbose_name='کد ملی مدیر')),
            ],
            options={
                'db_table': 'HR_RoleManager',
                'managed': False,
            },
        ),
    ]
