# Generated by Django 5.0.12 on 2025-05-17 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0072_v_hr_rolemanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='RoleType',
        ),
        migrations.AddField(
            model_name='role',
            name='RoleTypeCode',
            field=models.ForeignKey(db_column='RoleTypeCode', default='O', on_delete=django.db.models.deletion.CASCADE, to='HR.roletype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='ManagerType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.constvalue'),
        ),
    ]
