# Generated by Django 5.0.12 on 2025-05-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0073_remove_role_roletype_role_roletypecode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='ShortDescription',
            field=models.CharField(blank=True, db_column='ShortDescription', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='TeamDescription',
            field=models.TextField(blank=True, db_column='TeamDescription', null=True),
        ),
    ]
