# Generated by Django 5.0.12 on 2025-05-17 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0074_team_shortdescription_team_teamdescription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='UserSlip',
        ),
    ]
