# Generated by Django 5.0.12 on 2025-05-17 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0075_delete_payment_delete_userslip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YearNumber', models.IntegerField(verbose_name='سال')),
                ('Payment', models.BigIntegerField(blank=True, help_text='این مبلغ خالص دریافتی کاربر است', null=True, verbose_name='خالص دریافتی')),
                ('TotalPayment', models.BigIntegerField(blank=True, help_text='کل پرداختی ها شامل حقوق پایه، اضافه کار، پاداش و ...', null=True, verbose_name='حقوق ناخالص')),
                ('OtherPayment', models.BigIntegerField(blank=True, help_text='مثلا سوبسید ناهار تایم یا بیمه تکمیلی که شرکت برای این فرد پرداخت می کند', null=True, verbose_name='سایر هزینه های کارفرما')),
                ('PaymentCost', models.BigIntegerField(blank=True, help_text='بهای تمام شده فرد شامل کل حقوق دریافتی + بیمه کارفرما + سایر هزینه های پرداختی کارفرما است', null=True, verbose_name='بهای تمام شده این فرد')),
                ('BasePayment', models.BigIntegerField(blank=True, help_text='حقوق پایه یعنی مبلغ ناخالص قرارداد فرد', null=True, verbose_name='پایه حقوق')),
                ('OverTimePayment', models.BigIntegerField(blank=True, help_text='مبلغی که فرد بابت اضافه کار در ماه دریافت کرده است', null=True, verbose_name='هزینه اضافه کاری')),
                ('OverTime', models.IntegerField(blank=True, help_text='میزان اضافه کاری فرد بر حسب دقیقه', null=True, verbose_name='ساعت اضافه کاری')),
                ('Reward', models.BigIntegerField(blank=True, help_text='مبلغی که فرد به عنوان پاداش در آن ماه دریافت کرده است', null=True, verbose_name='مبلغ پاداش ماهانه')),
                ('PersonnelCode', models.CharField(max_length=10, verbose_name='کدملی')),
                ('MonthNumber', models.IntegerField(verbose_name='ماه')),
                ('InsuranceAmount', models.BigIntegerField(blank=True, db_column='InsuranceAmount', null=True)),
                ('DataType', models.SmallIntegerField(db_column='DataType')),
                ('Username', models.ForeignKey(db_column='Username', null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.users', verbose_name='نام کاربری')),
            ],
            options={
                'verbose_name': 'حقوق',
                'verbose_name_plural': 'حقوق های پرسنل',
                'db_table': 'HR_Payment',
            },
        ),
        migrations.CreateModel(
            name='UserSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YearNumber', models.IntegerField(verbose_name='سال')),
                ('MonthNumber', models.IntegerField(verbose_name='ماه')),
                ('ItemValue', models.BigIntegerField(verbose_name='مقدار مربوطه')),
                ('Code', models.CharField(max_length=200, verbose_name='کد مورد مربوطه')),
                ('PersonnelCode', models.CharField(max_length=10, verbose_name='کدملی')),
                ('Username', models.ForeignKey(db_column='Username', null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.users', verbose_name='نام کاربری')),
            ],
            options={
                'db_table': 'HR_UserSlip',
            },
        ),
    ]
