# Generated by Erfan Rezaee on 17 مه 2025، ساعت 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0076_payment_userslip'),
    ]

    with open("HR/SQLScripts/[dbo].[date_miladitoshamsi]1747503518.178908.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP FUNCTION [dbo].[date_miladitoshamsi]"
        )
    ]
