# Generated by Django 5.0.12 on 2025-05-19 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0076_payment_userslip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worktime',
            options={'verbose_name': 'اطلاعات چارگون', 'verbose_name_plural': 'اطلاعات چارگون'},
        ),
    ]
