# Generated by Django 5.0.12 on 2025-05-19 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0077_alter_worktime_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktime',
            name='UserName',
            field=models.ForeignKey(db_column='UserName', default='e', on_delete=django.db.models.deletion.CASCADE, related_name='WorkTimeUserNames', to='HR.users', verbose_name='نام کاربری'),
            preserve_default=False,
        ),
    ]
