# Generated by Erfan Rezaee on 19 مه 2025، ساعت 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0078_worktime_username'),
    ]

    with open("HR/SQLScripts/[dbo].[date_miladitoshamsi]1747675656.049494.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP FUNCTION [dbo].[date_miladitoshamsi]"
        )
    ]
