# Generated by Erfan Rezaee on 17 مه 2025، ساعت 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0078_FUNCTION_dbo_date_reversdate_1747503518_256954_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[date_shamsidateadd]1747503518.286022.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP FUNCTION [dbo].[date_shamsidateadd]"
        )
    ]
