# Generated by Erfan Rezaee on 19 مه 2025، ساعت 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0079_FUNCTION_dbo_date_miladitoshamsi_1747675656_049494_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[date_reversdate]1747675656.097644.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP FUNCTION [dbo].[date_reversdate]"
        )
    ]
