# Generated by Erfan Rezaee on 17 مه 2025، ساعت 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0079_FUNCTION_dbo_date_shamsidateadd_1747503518_286022_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[date_shamsidatediff]1747503518.367819.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP FUNCTION [dbo].[date_shamsidatediff]"
        )
    ]
