# Generated by Erfan Rezaee on 17 مه 2025، ساعت 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0080_FUNCTION_dbo_date_shamsidatediff_1747503518_367819_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[date_shamsitomiladi]1747503518.444187.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP FUNCTION [dbo].[date_shamsitomiladi]"
        )
    ]
