# Generated by Erfan Rezaee on 19 مه 2025، ساعت 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0081_FUNCTION_dbo_date_shamsidateadd_1747675656_135874_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[date_shamsidatediff]1747675656.179935.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP FUNCTION [dbo].[date_shamsidatediff]"
        )
    ]
