# Generated by Erfan Rezaee on 19 مه 2025، ساعت 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0082_FUNCTION_dbo_date_shamsidatediff_1747675656_179935_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[date_shamsitomiladi]1747675656.213664.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP FUNCTION [dbo].[date_shamsitomiladi]"
        )
    ]
