# Generated by Erfan Rezaee on 17 مه 2025، ساعت 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0082_FUNCTION_dbo_date_substrcount_1747503518_469104_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[date_workhistory]1747503518.533781.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP FUNCTION [dbo].[date_workhistory]"
        )
    ]
