# Generated by Erfan Rezaee on 17 مه 2025، ساعت 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0083_FUNCTION_dbo_date_workhistory_1747503518_533781_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[eva_date_reversdate]1747503518.559656.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP FUNCTION [dbo].[eva_date_reversdate]"
        )
    ]
