# Generated by Erfan Rezaee on 19 مه 2025، ساعت 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0084_FUNCTION_dbo_date_substrcount_1747675656_272704_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[date_workhistory]1747675656.322803.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP FUNCTION [dbo].[date_workhistory]"
        )
    ]
