# Generated by Erfan Rezaee on 19 مه 2025، ساعت 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0085_FUNCTION_dbo_date_workhistory_1747675656_322803_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[eva_date_reversdate]1747675656.369311.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP FUNCTION [dbo].[eva_date_reversdate]"
        )
    ]
