# Generated by Erfan Rezaee on 17 مه 2025، ساعت 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0085_FUNCTION_dbo_eva_date_shamsitomiladi_1747503518_630136_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[eva_date_substrcount]1747503518.656603.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP FUNCTION [dbo].[eva_date_substrcount]"
        )
    ]
