# Generated by Erfan Rezaee on 17 مه 2025، ساعت 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0086_FUNCTION_dbo_eva_date_substrcount_1747503518_656603_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[getalluserteamrole]1747503518.852393.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP FUNCTION [dbo].[getalluserteamrole]"
        )
    ]
