# Generated by Erfan Rezaee on 19 مه 2025، ساعت 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0086_FUNCTION_dbo_eva_date_reversdate_1747675656_369311_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[eva_date_shamsitomiladi]1747675656.414236.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP FUNCTION [dbo].[eva_date_shamsitomiladi]"
        )
    ]
