# Generated by Erfan Rezaee on 17 مه 2025، ساعت 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0087_FUNCTION_dbo_getalluserteamrole_1747503518_852393_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[hr_converttimetominutes]1747503518.960796.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP FUNCTION [dbo].[hr_converttimetominutes]"
        )
    ]
