# Generated by Erfan Rezaee on 17 مه 2025، ساعت 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0088_FUNCTION_dbo_hr_converttimetominutes_1747503518_960796_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[hr_getteammembercount]1747503519.048088.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP FUNCTION [dbo].[hr_getteammembercount]"
        )
    ]
