# Generated by Erfan Rezaee on 19 مه 2025، ساعت 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0088_FUNCTION_dbo_eva_date_substrcount_1747675656_465919_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[getalluserteamrole]1747675656.535424.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP FUNCTION [dbo].[getalluserteamrole]"
        )
    ]
