# Generated by Erfan Rezaee on 17 مه 2025، ساعت 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0089_FUNCTION_dbo_hr_getteammembercount_1747503519_048088_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[hr_name_getteammanager]1747503519.144885.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP FUNCTION [dbo].[hr_name_getteammanager]"
        )
    ]
