# Generated by Erfan Rezaee on 17 مه 2025، ساعت 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0090_FUNCTION_dbo_hr_name_getteammanager_1747503519_144885_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[users]1747503519.250695.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="SELECT 1"
        )
    ]
