# Generated by Erfan Rezaee on 17 مه 2025، ساعت 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0091_VIEW_dbo_users_1747503519_250695_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[team]1747503519.342795.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="SELECT 1"
        )
    ]
