# Generated by Erfan Rezaee on 17 مه 2025، ساعت 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0092_VIEW_dbo_team_1747503519_342795_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[userfullinformation_view]1747503519.792145.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP VIEW [dbo].[userfullinformation_view]"
        )
    ]
