# Generated by Erfan Rezaee on 19 مه 2025، ساعت 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0092_FUNCTION_dbo_hr_name_getteammanager_1747675656_69771_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[users]1747675656.885138.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP VIEW [dbo].[users]"
        )
    ]
