# Generated by Erfan Rezaee on 19 مه 2025، ساعت 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0093_VIEW_dbo_users_1747675656_885138_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[team]1747675656.952356.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP VIEW [dbo].[team]"
        )
    ]
