# Generated by Erfan Rezaee on 17 مه 2025، ساعت 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0093_VIEW_dbo_userfullinformation_view_1747503519_792145_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[v_alluserlist]1747503520.280082.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP VIEW [dbo].[v_alluserlist]"
        )
    ]
