# Generated by Erfan Rezaee on 19 مه 2025، ساعت 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0094_VIEW_dbo_team_1747675656_952356_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[userfullinformation_view]1747675657.119306.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP VIEW [dbo].[userfullinformation_view]"
        )
    ]
