# Generated by Erfan Rezaee on 17 مه 2025، ساعت 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0094_VIEW_dbo_v_alluserlist_1747503520_280082_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[hr_rolemanager]1747503520.37413.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP VIEW [dbo].[hr_rolemanager]"
        )
    ]
