# Generated by Erfan Rezaee on 17 مه 2025، ساعت 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0095_VIEW_dbo_hr_rolemanager_1747503520_37413_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[v_payment_average]1747503520.593477.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP VIEW [dbo].[v_payment_average]"
        )
    ]
