# Generated by Erfan Rezaee on 19 مه 2025، ساعت 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0095_VIEW_dbo_userfullinformation_view_1747675657_119306_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[v_alluserlist]1747675657.343499.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP VIEW [dbo].[v_alluserlist]"
        )
    ]
