# Generated by Erfan Rezaee on 17 مه 2025، ساعت 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0096_VIEW_dbo_v_payment_average_1747503520_593477_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[v_worktime]1747503520.982455.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP VIEW [dbo].[v_worktime]"
        )
    ]
