# Generated by Erfan Rezaee on 19 مه 2025، ساعت 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0096_VIEW_dbo_v_alluserlist_1747675657_343499_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[hr_rolemanager]1747675657.416351.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP VIEW [dbo].[hr_rolemanager]"
        )
    ]
