# Generated by Erfan Rezaee on 17 مه 2025، ساعت 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0097_VIEW_dbo_v_worktime_1747503520_982455_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[userteamroleall]1747503521.19921.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP VIEW [dbo].[userteamroleall]"
        )
    ]
