# Generated by Erfan Rezaee on 19 مه 2025، ساعت 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0097_VIEW_dbo_hr_rolemanager_1747675657_416351_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[v_payment_average]1747675657.584693.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP VIEW [dbo].[v_payment_average]"
        )
    ]
