# Generated by Erfan Rezaee on 17 مه 2025، ساعت 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0098_VIEW_dbo_userteamroleall_1747503521_19921_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[changeuserteamrole]1747503521.299398.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP VIEW [dbo].[changeuserteamrole]"
        )
    ]
