# Generated by Erfan Rezaee on 19 مه 2025، ساعت 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0098_VIEW_dbo_v_payment_average_1747675657_584693_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[v_worktime]1747675657.695905.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP VIEW [dbo].[v_worktime]"
        )
    ]
