# Generated by Erfan Rezaee on 19 مه 2025، ساعت 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0099_VIEW_dbo_v_worktime_1747675657_695905_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[userteamroleall]1747675657.872491.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP VIEW [dbo].[userteamroleall]"
        )
    ]
