# Generated by Erfan Rezaee on 19 مه 2025، ساعت 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0100_VIEW_dbo_userteamroleall_1747675657_872491_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[changeuserteamrole]1747675657.959254.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP VIEW [dbo].[changeuserteamrole]"
        )
    ]
