# Generated by Erfan Rezaee on 19 مه 2025، ساعت 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0101_VIEW_dbo_changeuserteamrole_1747675657_959254_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[userwithoutteamrole]1747675658.018458.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP VIEW [dbo].[userwithoutteamrole]"
        )
    ]
