# Generated by Erfan Rezaee on 17 مه 2025، ساعت 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0101_VIEW_dbo_changeteamrolejson_1747503521_409391_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[userteamrolejson]1747503521.512475.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP VIEW [dbo].[userteamrolejson]"
        )
    ]
