# Generated by Erfan Rezaee on 19 مه 2025، ساعت 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0102_VIEW_dbo_userwithoutteamrole_1747675658_018458_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[changeteamrolejson]1747675658.082121.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP VIEW [dbo].[changeteamrolejson]"
        )
    ]
