# Generated by Erfan Rezaee on 17 مه 2025، ساعت 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0102_VIEW_dbo_userteamrolejson_1747503521_512475_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[v_pagepermission]1747503522.250949.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP VIEW [dbo].[v_pagepermission]"
        )
    ]
