# Generated by Erfan Rezaee on 17 مه 2025، ساعت 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0103_VIEW_dbo_v_pagepermission_1747503522_250949_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[auth_userteamrole]1747503522.47956.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP VIEW [dbo].[auth_userteamrole]"
        )
    ]
