# Generated by Erfan Rezaee on 17 مه 2025، ساعت 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0104_VIEW_dbo_auth_userteamrole_1747503522_47956_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[keymembers]1747503522.642134.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP VIEW [dbo].[keymembers]"
        )
    ]
