# Generated by Erfan Rezaee on 19 مه 2025، ساعت 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0104_VIEW_dbo_userteamrolejson_1747675658_141432_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[v_pagepermission]1747675658.570089.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP VIEW [dbo].[v_pagepermission]"
        )
    ]
