# Generated by Erfan Rezaee on 19 مه 2025، ساعت 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0105_VIEW_dbo_v_pagepermission_1747675658_570089_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[auth_userteamrole]1747675658.660686.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP VIEW [dbo].[auth_userteamrole]"
        )
    ]
