# Generated by Erfan Rezaee on 17 مه 2025، ساعت 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0105_VIEW_dbo_keymembers_1747503522_642134_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[v_payment_role_average]1747503522.734271.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP VIEW [dbo].[v_payment_role_average]"
        )
    ]
