# Generated by Erfan Rezaee on 19 مه 2025، ساعت 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0106_VIEW_dbo_auth_userteamrole_1747675658_660686_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[keymembers]1747675658.775576.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP VIEW [dbo].[keymembers]"
        )
    ]
