# Generated by Erfan Rezaee on 19 مه 2025، ساعت 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0108_VIEW_dbo_v_payment_role_average_1747675658_839672_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[v_payment_yearly]1747675658.910324.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP VIEW [dbo].[v_payment_yearly]"
        )
    ]
