# Generated by Erfan Rezaee on 19 مه 2025، ساعت 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0109_VIEW_dbo_v_payment_yearly_1747675658_910324_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[v_hr_roletarget]1747675659.074194.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP VIEW [dbo].[v_hr_roletarget]"
        )
    ]
