# Generated by Erfan Rezaee on 17 مه 2025، ساعت 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0110_VIEW_dbo_v_roleteam_1747503523_508566_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[v_payment_role_average_yearly]1747503523.598591.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP VIEW [dbo].[v_payment_role_average_yearly]"
        )
    ]
