# Generated by Erfan Rezaee on 17 مه 2025، ساعت 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0111_VIEW_dbo_v_payment_role_average_yearly_1747503523_598591_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[v_userslip_average]1747503523.743535.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP VIEW [dbo].[v_userslip_average]"
        )
    ]
