# Generated by Erfan Rezaee on 17 مه 2025، ساعت 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0112_VIEW_dbo_v_userslip_average_1747503523_743535_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[corectinputdata]1747503535.068052.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP PROCEDURE [dbo].[corectinputdata]"
        )
    ]
