# Generated by Erfan Rezaee on 17 مه 2025، ساعت 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0113_PROCEDURE_dbo_corectinputdata_1747503535_068052_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[hr_getassessorsandeducators]1747503535.189223.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP PROCEDURE [dbo].[hr_getassessorsandeducators]"
        )
    ]
