# Generated by Erfan Rezaee on 19 مه 2025، ساعت 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0114_VIEW_dbo_v_userslip_average_1747675659_584111_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[corectinputdata]1747675668.378075.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP PROCEDURE [dbo].[corectinputdata]"
        )
    ]
