# Generated by Erfan Rezaee on 17 مه 2025، ساعت 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0116_PROCEDURE_dbo_hr_gettargetrole_1747503535_317561_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[hr_getteammanager]1747503535.36777.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP PROCEDURE [dbo].[hr_getteammanager]"
        )
    ]
