# Generated by Erfan Rezaee on 19 مه 2025، ساعت 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0117_PROCEDURE_dbo_hr_getchoiceassessorsandeducators_1747675668_599804_GIS_SCRIPT'),
    ]

    with open("HR/SQLScripts/[dbo].[hr_gettargetrole]1747675668.68184.sql", "r", encoding="utf-8") as f:
        sql = f.read()
    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql="DROP PROCEDURE [dbo].[hr_gettargetrole]"
        )
    ]
