# Generated by Django 4.0.1 on 2024-10-14 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='نام کاربر')),
                ('Title', models.CharField(max_length=500, verbose_name='نام دسته بندی')),
                ('Icon', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='ایکون')),
                ('OrderNumber', models.IntegerField(blank=True, null=True, verbose_name='ترتیب')),
                ('Parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SystemCategoryParents', to='Systems.systemcategory', verbose_name='نام دسته بندی پدر')),
            ],
        ),
        migrations.CreateModel(
            name='SystemCategoryURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppURL', models.BigIntegerField(null=True)),
                ('SystemCategory', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SystemCategoryURLSystemCategorys', to='Systems.systemcategory', verbose_name='دسته بندی برنامه')),
            ],
        ),
    ]
