# Generated by Django 4.0.1 on 2022-05-02 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HR', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RequestStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RoleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=100, verbose_name='دسته بندی')),
                ('DescriptionType', models.CharField(choices=[('C', 'شرایط احراز'), ('D', 'شرح وظایف')], max_length=1, verbose_name='نوع')),
            ],
            options={
                'verbose_name': 'دسته بندی سمت',
                'verbose_name_plural': 'دسته بندی های سمت',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('ModifyDate', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ویرایش')),
                ('Permission', models.IntegerField(verbose_name='دسترسی')),
                ('CreatorUserName', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_cr', to='HR.users', verbose_name='ایجاد کننده')),
                ('ModifierUserName', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_md', to='HR.users', verbose_name='ویرایش کننده')),
                ('Role', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='HR.role', verbose_name='سمت')),
            ],
            options={
                'verbose_name': 'دسترسی سمت',
                'verbose_name_plural': 'دسترسی سمت ها',
            },
        ),
        migrations.CreateModel(
            name='RoleDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('ModifyDate', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ویرایش')),
                ('Superior', models.BooleanField(default=False, verbose_name='ارشد')),
                ('Title', models.CharField(max_length=4000, verbose_name='شرح')),
                ('IsConfirm', models.BooleanField(default=False, verbose_name='تایید')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Duties.rolecategory', verbose_name='نوع')),
                ('CreatorUserName', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_cr', to='HR.users', verbose_name='ایجاد کننده')),
                ('LevelId', models.ForeignKey(db_column='LevelId', null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.rolelevel', verbose_name='شناسه سطح')),
                ('ModifierUserName', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_md', to='HR.users', verbose_name='ویرایش کننده')),
                ('RoleId', models.ForeignKey(db_column='RoleId', null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.role', verbose_name='شناسه سمت')),
            ],
            options={
                'verbose_name': 'توضیحات سمت',
                'verbose_name_plural': 'توضیحات سمت ها',
            },
        ),
    ]
