# Generated by Django 4.0.1 on 2022-03-09 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Duties', '__first__'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Request',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='RequestStep',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Step',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #     ],
        # ),
        migrations.AlterField(
            model_name='roledescription',
            name='CreatorUserName',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_cr', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
        ),
        migrations.AlterField(
            model_name='roledescription',
            name='ModifierUserName',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_md', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش کننده'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='CreatorUserName',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_cr', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='ModifierUserName',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_md', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش کننده'),
        ),
    ]
