# Generated by Django 4.0.1 on 2022-02-06 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        #('AccessControl', '__first__'),
        ('HR', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppDocId', models.IntegerField(verbose_name='شناسه')),
                ('Priority', models.CharField(max_length=100, verbose_name='اولویت')),
                ('DocState', models.CharField(max_length=100, verbose_name='وضعیت')),
                #('AppURLId', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AppURLs', to='AccessControl.appurl', verbose_name='مسیر برنامه')),
                ('AppCode', models.CharField(max_length=200,blank=True,null=True )),
            ],
        ),
        migrations.CreateModel(
            name='DocumenrFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReciveDate', models.DateField(blank=True, null=True, verbose_name='تاریخ دریافت')),
                ('IsRead', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('SendDate', models.DateField(blank=True, null=True, verbose_name='تاریخ ارسال')),
                ('DueDate', models.DateField(blank=True, null=True, verbose_name='مهلت پاسخ گویی')),
                ('PersonalDueDate', models.DateField(blank=True, null=True, verbose_name='زمان انجام کار')),
                ('DocumentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Documents', to='Cartable.document', verbose_name='شناسه ')),
                ('InboxOwner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='InboxOwners', to='HR.users', verbose_name='کاربر')),
                ('PreviousFlow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DocumenrFlows', to='Cartable.documenrflow', verbose_name='قبلی ')),
                ('SenderUser', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='SenderUsers', to='HR.users', verbose_name='کاربر ارسال کننده')),
            ],
        ),
    ]
