# Generated by Django 4.0.1 on 2022-03-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartable', '0002_rename_documenrflow_documentflow_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentflow',
            old_name='ReciveDate',
            new_name='ReceiveDate',
        ),
        migrations.AddField(
            model_name='document',
            name='DocumentTitle',
            field=models.CharField(max_length=500, null=True, verbose_name='نوع'),
        ),
    ]
