# Generated by Django 4.0.1 on 2022-03-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartable', '0003_rename_recivedate_documentflow_receivedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='IsVisible',
            field=models.BooleanField(default=True, verbose_name='قابل مشاهده'),
        ),
    ]
