# Generated by Django 4.0.1 on 2022-03-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartable', '0004_document_isvisible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='IsVisible',
        ),
        migrations.AddField(
            model_name='documentflow',
            name='IsVisible',
            field=models.BooleanField(default=True, verbose_name='قابل مشاهده'),
        ),
    ]
