# Generated by Django 4.0.1 on 2022-05-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartable', '0005_remove_document_isvisible_documentflow_isvisible'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='document',
        #     name='AppCode_id',
        #     field=models.CharField(blank=True, max_length=200, null=True, verbose_name='مسیر برنامه'),
        # ),
    ]
