# Generated by Django 4.0.1 on 2022-05-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartable', '0006_alter_document_appcode'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='document',
        #     name='AppCode1',
        #     field=models.CharField(blank=True, max_length=200, null=True, verbose_name='مسیر برنامه'),
        # ),
    ]
