# Generated by Django 4.0.1 on 2022-05-05 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cartable', '0007_document_appcode1'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='document',
        #     old_name='AppCode_id',
        #     new_name='AppCode',
        # ),
    ]
