# Generated by Django 4.0.1 on 2022-05-05 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cartable', '0008_rename_appcode_id_document_appcode'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='document',
        #     name='AppCode',
        # ),
    ]
