# Generated by Django 4.0.1 on 2022-05-05 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cartable', '0009_remove_document_appcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='AppCode1',
            new_name='AppCode',
        ),
    ]
