# Generated by Django 4.0.1 on 2022-05-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartable', '0010_rename_appcode1_document_appcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='AppCode',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='مسیر برنامه'),
        ),
    ]
